Reporter Jennifer Griffin has been on the road , heading south from Beirut , and she joins us by phone from Tyre .
Good morning , Jennifer .
Hello .
What are you seeing on the coast road as you head south from Beirut ?
the cars are jam-packed bumper to bumper all the way from Beirut to Tyre .
People are packed 10 and 12 per car .
They have mattresses strapped to the roofs of their car because they 're not sure what they 're going to see when they get to the other end.
They 're not sure whether their houses survived the bombing attacks and they 're not sure where they 're going to sleep tonight .
There are people who have tied black ribbons to their antennas in memory of the people who have died in the last 16 days .
how much faith do they put in this cease-fire ?
the people of Lebanon , they 've seen war and they 've seen broken cease-fires , but they think this cease-fire is going to hold .
it 's going to last , but for how long .
people feel that it 's only a matter of time before the hostilities reach a level where there 's more fighting .
How bad is the destruction in Southern Lebanon ?
Are the roads open ?
Are the villages habitable ?
It 's unbelievable .
The roads from Tyre to the smaller villages are cratered with bomb holes where rockets and shells have fallen .
most of the roads are impassable , and a lot of the cars are being stopped and made to wait while the U.N. tries to make alternative routes , but it 's difficult because these are mountainous areas .
The destruction is massive .
many homes along the route are just rubble and that , combined with the craters in the road , it 's quite a scene .
What about reconstruction ?
It 's early yet , but are there plans to begin reconstructing ?
Yeah , there are plans .
The French have had a presence here since the fighting began and they 've vowed to help with the electric transformers that were destroyed when the Israelis bombed Beirut , and they 've offered to bring two transformers in , but the government estimates it 'll cost $ 80 million to get the electricity back up and running .
What did the future look like to the people you 're speaking with ?
people are trying to get on with their lives .
They 're worried about their homes and already people are sweeping out the homes , trying to make them livable .
I talked to one boy who was hit by an Israeli shell .
He was sitting in the second floor of his house , and his face is scarred from the burns from that attack , and he and his family ca n't reach their home because the road is destroyed , but they 're waiting for the U.N. to help them .
his house looks like a carton with the edges folded in , and next time Israeli shells fall , he 's going to join Hezbollah .
Thanks , Jennifer .
Thanks , Neal .
Jennifer Griffin from Tyre , Lebanon .
The Whitewater verdicts have caused an embarrassment for Arkansas ' Republican Lieutenant Governor , Mike Huckabee .
Since Democratic Governor Jim Guy Tucker is resigning , Huckabee will be taking over the governor 's office .
But Huckabee is the GOP nominee for a U.S. Senate seat .
Is a statehouse in the hand worth a senate seat in the Beltway ?
Huckabee will let everybody know tomorrow .
Whether he is heeding strategists ' advice or his own instincts , Bob Dole is staying mum about the Whitewater verdicts .
he has not been silent about crime and the president 's record on it.
Tomorrow Mr. Clinton will endorse the right of communities to use curfews to curb violence .
It was an issue Dole addressed today .
More from Candy Crowley .
On a campaign swing through California , Dole stopped in a Southern California park to speak in praise of anti-gang efforts .
They made it work , because they got tired of it.
They wanted their children to enjoy the parks , not the criminals , They were n't built for criminals , they were built for you .
Crime is the focal point of Dole 's trip to California .
Mr. President , I 'm sorry you took off three years .
You were AWOL for three years .
You were without leadership on the drug program for three years , and election year conversion is not going to do any good .
This trip had overriding .
Dole is here , not for the first time .
Not for the last .
we 're going to come to California - whatever it takes , we want to win this state .
But no trip to California will be more important to Dole than the one in August .
Dole dropped by the San Diego Convention Center for a peek at the place where he will become the Republican nominee for president .
-have a great party here .
It 's going to be a start on the road to victory .
Being here is important to California Republicans , who think they lost local seats when George Bush abandoned the state months ahead of the election .
Ken Kachigian , in charge of Dole 's California efforts , says , step one is showing up.
step two is to have an aggressive campaign defining- we have to redefine President Clinton , we have to start letting people get exposed to Bob Dole .
it 's a big hill , a long trip .
The Dole campaign hopes to pick up support on three issues of California politics - crime , border patrol , and affirmative action .
Dole supports a California initiative which would dismantle most affirmative action programs .
As for Whitewater , Dole will let others parse the politics .
As Kachigian put it , when there 's a freight train coming down the tracks , it does n't make sense to stand in the way of it.
Candy Crowley , CNN , Redondo Beach , California .
Breaking news from the Air Force on the wake of the crash that killed Commerce Secretary Ron Brown and the troupe that was traveling with him .
We go now to Carl Rochelle , at the White House this morning , for that latest on that .
Carl .
the three most-immediate commanders in charge of that airplane have been fired by the Air Force .
Major General Charles Heffelbauer , the commander of the 17th Air Force in Europe has lost confidence in the ability of the commander , the vice-commander , and the group operations commander of the 86th Airlift Wing and relieved those men of duty Wednesday evening .
That was with the concurrence of the commander of U.S. forces in Europe , General Michael Ryan .
The officers relieved were Brigadier General William Stevens , Colonel Roger W. Hanson , and Colonel John E. Mazurowsky .
the men are being immediately replaced , but there are no further details available as to the reasons why .
they wo n't release any details of what led them to take this action until after the investigation is completed and the results are released .
But again , the three senior commanders who were involved in the oversight have been relieved of duty .
Leon .
All right .
if you can tell us if any of their subordinates are also going to be charged or if there are going to be any other shoes dropping for anyone beneath these gentlemen ?
there have n't been any charges .
when the unit fails in its mission , then the senior people in charge have to take the brunt for that because beneath them the actions were n't taken , the orders were n't given , the right personnel were n't in place to perform the mission .
It is unclear what they found in that investigation .
they never have come down with a reason for the crash .
the aircraft was off course .
It was not flying to the , but went off in the mountains .
the transportation command inside the United States had ruled that airport only safe for landing , during VFR day-time weather .
but not at night and not in inclement conditions .
the unit in Europe had not done that , so that 's one area that might be into question .
some of the training and procedures might be into questions .
That remains to be seen .
All right .
if you can tell us where the brigadier general and the two colonels are right now ?
Do you know ?
The names of the-
Do you know where they are ?
Do you know where they are ?
do I know where they are ?
They have not been sent back to the United States .
OK.
they 're still in Europe .
All right .
Thanks .
Carl Rochelle live from the White House .
Thanks , we 'll see you .
Direct talks did n't work , and mediators did n't help .
Now the FBI may be turning to a religious expert to end the Freemen standoff in Montana .
A member of a religious think tank from Houston is meeting with federal agents .
Don Knapp joins us live from Montana with .
Don ?
no sign of activity on the Freemen ranch ; no sign of any activity on the part of the FBI .
work is continuing to put generators on the neighboring ranches so that the FBI will be able to shut off power to the Freemen .
But there is some activity underway .
The FBI has brought in a religious expert .
He is Philip Arnold , an associate at the Reunion Institute in Houston and a member of the Religious Freedom Task Force .
He is consulting with the FBI and they have not ruled out his acting as a negotiator .
They say that he is an expert on this sort of situation .
He 's been critical of the federal government 's handling of the incident at Waco that cost so many lives .
in Billings , Montana , there was a hearing for two of the Freemen whose arrests triggered this standoff , along with three other associates .
The hearing became unruly .
Two Freemen were evicted from the courtroom , and the judge did grant the prosecution more time to prepare for trial .
Bobbie ?
Don Knapp near Brusett , Montana , thanks very much .
What could be more frustrating than wasting time in traffic ?
imagine a future where you could read a book while a computer takes the wheel .
the era of automated driving could be down the road .
Pull up alongside a vehicle of the future and take a look inside Researchers call them Smart Cars and they could give the phrase `` back seat driver ' a new meaning .
the goal of the automated highway system- is to allow a commuter to sit back and catch up on work , make phone calls .
Scientists have been building prototypes of automated , driver-less vehicles for 10 years .
Five years ago , Nav Lab Two was a Humvee , loaded down with computers and camera systems .
The gear enabled the program to see the road .
Nav Lab Five is a streamlined package that fits into a sedan , and its systems can help if there 's someone at the wheel .
These vehicles are designed for automated steering , but also to monitor human drivers ' performance , to warn them if they 're going to get in an accident .
if I start to drift to the inside , it 'll trigger an alarm as soon as one of the tires gets outside the lane boundary .
The system relies on a video camera inside the car to see what 's going on outside .
It looks for lane markers to help keep the car and the driver on the road .
The camera 's mounted below the rear view mirror and looks at a trapezoidal shape 20 meters ahead of the vehicle .
The image is analyzed by a portable computer workstation mounted inside the car powered by the cigarette lighter .
In a test , a Nav Lab van traveled from Washington to San Diego .
More than 90 percent of the trip was driven and controlled by the computer , everything but the breaks .
there were bumps in the road .
It has trouble in situations that human drivers sometimes have trouble in .
one of the most difficult situations is a rainy night with on-coming headlights blinding you because of the reflections off the roadway .
Researchers expect it will be another 10 years before they get the bugs worked out of an automated driving system , but the accident warning program could be added to existing vehicles within two years , initially to trucks which have a high accident rate .
One in four trucks are involved in this kind of accident within their lifetime , so it would be a win for trucking companies if we could sell it for $ 2,000 .
The goal is to make the highways safer by keeping an eye on the road and two hands off the wheel .
Dick Wilson , CNN , Pittsburgh , Pennsylvania .
Questions about the future of the Middle East peace process will be addressed by the man who may have the answers .
Israel 's new prime minister , Benjamin Netanyahu , will outline his policies Sunday .
He spent the Jewish Sabbath with family and friends .
the White House is trying to calm Netanyahu 's critics .
Netanyahu 's victory jarred many in the Arab world , but the Clinton administration has been in touch with Arab leaders , reassuring them the U.S. will continue its efforts at peace and urging them not to pre-judge the prime minister .
President Clinton said , `` Give him time . '
we ought to give the new prime minister a chance to put his government together and develop a policy .
he wants to continue the process and I hope that the friends of peace in the Arab world will be committed to that .
Mr. Clinton cited comments by Netanyahu and a phone conversation .
The president was encouraged by public comments from Jordan 's King Hussein whom Netanyahu telephoned after his victory .
he was going to do whatever he could to bring on the subject towards our objective of peace in this area .
Netanyahu opposed return of the Golan Heights to Syria and creation of a Palestinian state .
the prime minister knows it 's in Israel 's interest to preserve the gains it has made from the peace process and to maintain a good relationship with its neighbors .
I do n't think Netanyahu intends to kill the peace process .
he intends to bargain harder and not make many concessions .
the world will not come to an end.
The Clinton administration has a vested interest in downplaying any setback to the peace process .
President Clinton has pinned a part of his international policy reputation on it.
Russian voters decide the fate of Boris Yeltsin two weeks from now .
Jill Dougherty , CNN , the White House .
It was home to Al Capone , and the Birdman of Alcatraz .
For 30 years , the prison in San Francisco Bay housed the worst criminals in the U.S.
Now the prison know as `` The Rock ' goes from the big house to the big screen , again .
Movie goers are gearing up to enter The Rock starring Sean Connery , Nicholas Cage , and Ed Harris .
They shot much of this tale on Alcatraz , the prison that housed some of the most savage inmates ever to serve time .
Alcatraz is an unsafe place to make a movie , because there are cliffs and rotting , corroding steel pipes everywhere , and old nails sticking up.
Alcatraz opened in 1934 , was shut down in 1963 due to its deteriorating conditions .
in the early stages of filming The Rock , it 's creepy .
sometimes you 're alone in the main cell block and you 're seeing , Al Capone lived here- it 's bizarre .
these cells are really small .
They 're five by seven , and they 're low ceilings .
They 're six-something .
Bay 's film is not the first time Hollywood has romanced the stone .
last year , Kevin Bacon and Christian Slater probed brutality on Alcatraz in Murder In The First .
Burt Lancaster received an Oscar nomination for Birdman of Alcatraz , while Clint Eastwood chipped away at the Rock in Escape From Alcatraz .
Escape ?
That 's what Sean Connery 's character did in the latest Alcatraz movie .
His name is John Mason , incarcerated on Alcatraz in 1962 .
The government needs Mason 's knowledge of the prison and the expertise of an FBI scientist played by Cage .
It 's a problem .
it 's like anything Stan Goodspeed has encountered before .
the San Francisco Bay area is in jeopardy .
We 've put him in a circumstance where he wants to survive and get out of it and he 's sucked in by this guy whose ill-equipped for this job .
The job is to end a chemical weapons threat against the Bay Area by a general played by Ed Harris .
You 're right .
I do n't use guns and I do n't kick down doors .
This is what I do .
I have n't got my glasses .
The combination of Connery and Cage provides relief from rapidfire cuts and moving shots .
His and my character were perfect combination to get laughs .
these actors traded lines where inmates once traded insults .
Paul Vercammen , CNN Entertainment News , Los Angeles .
During the summit meetings , Secretary of State Warren Christopher and Treasury Secretary Lloyd Bentsen dropped in on the inaugural meeting of the American Chamber of Commerce in Moscow and offered encouragement .
Instead of aid , the Clinton administration is pushing private Americans investment .
loan guarantees for American businesses have finally kicked in , but American businessmen in Russia still feel like pioneers .
Anne Garrels reports .
Five years ago Alex Papacristo was one of the few American lawyers in Moscow and the only one representing his firm , White & Case .
Now the office has 12 lawyers .
The capital is awash in consultants and accountants .
Hotels have sprung up catering to Western businessmen .
The break-up of the Communist Party and its throttle hold has expanded business opportunities , too much order has been replaced with too much chaos .
top officials , even if they want to help , ca n't really help because they do n't control things .
Nobody does .
the problem is reversed today as it was then .
There 's no order , and it 's hard to determine whether you 're talking to the right person , whether he has the rights to do what he says he 's doing .
Take the development of a major oil shelf off the coast of Sakhalin Island .
assertive regional leaders balked at the deal the central government had approved .
Parliament got into the act.
Only after several years did American oil companies have a contract .
Foreign companies are frustrated by changing laws , arbitrary regulations , ineffectual courts , and a lack of infrastructure .
Yet for all the chaos , Papacristo remains intrigued .
The ability to invest in privatized Russian companies is the exciting activity .
There 's more of that .
It 's in the order of hundreds of millions of dollars , which , compared to American business in other countries , is not huge .
But it 's getting bigger .
the lessons learned are start small and find a good partner .
Donald Green , managing director of the consulting firm Planicon , says business in Russia requires time and spade work .
You have companies who develop their distribution capability where they 're not manufacturing in Russia but they 're developing the networks to be able to sell their products throughout the Russian federation .
As order breaks down , theft becomes a problem .
If you are moving cigarettes or alcohol or perfume around Russia , the security of those shipments is of major concern .
I do n't regard those circumstances as threatening or dangerous as the worst stories of developing business around the world , but they 're significant .
Recent election results sent chills to the American business community , but Papacristo and Green are optimistic Yeltsin will stop the parliament from making the situation worse .
While American investment in Russia is unlikely to explode , both expect a steady increase .
both warn investment in Russia is not for the faint-hearted or the impatient .
I 'm Anne Garrels in Washington .
It 's All Things Considered .
I 'm Noah Adams .
I 'm Linda Wertheimer .
In Israel , Benjamin Netanyahu was declared the winner of last week 's election .
The prime minister-elect has 45 days to form a new government .
One of Netanyahu 's first tasks is to select his cabinet members .
the people he chooses will determine the future course of the Middle East peace process .
Benjamin Netanyahu needed support to win last week 's election .
he 's under pressure to reward those who helped him , namely Israel 's ultra-Orthodox Jews and hard liners from within his Likud Party .
David Makovsky , author of a book on the Oslo peace accord , says Netanyahu 's policies will depend on the people he decides to appoint .
is the pragmatic Netanyahu that we saw on the campaign trail gonna be the pragmatic leader we see while he serves as prime minister ?
the Likud is a mixture of pragmatists , which Netanyahu 's one of , and ideologues .
Those ideologues include Rafael Eytan and Ariel Sharon , who orchestrated Israel 's invasion of Lebanon in 1982 .
Sharon played a key role in Netanyahu 's campaign , and he 's reportedly insisting on a top cabinet position .
Representatives from religious parties are likely to receive at least two cabinet positions .
moderate Likud leaders are also in line for top posts .
David Levy , foreign minister during the Party 's last time in office , is likely to get his old job .
Another question is whether Netanyahu will be willing to share power with Shimon Peres .
Israel 's two major parties have governed together before , and Yossi Beilin , a minister in the Peres government , says , given the status of the peace process , it 's worth trying .
I think that it is the most delicate moment in our history , in the peace process , because we are going to refer to issues like the refugees , Jerusalem , the borders , and it is very important that we be there and help .
I 'm sure that it is possible to find a solution which might become a common denominator for the Palestinians , the Labor Party , and the Likud .
But Netanyahu has yet to propose a national unity government , nor has Peres expressed any enthusiasm for the idea .
Analysts say a power-sharing arrangement is possible , though unlikely .
Netanyahu is meeting not only with potential coalition partners , but with foreign ambassadors , including U.S. Ambassador Martin Indyk .
The main topic of discussion was Netanyahu 's upcoming trip to Washington .
The president is keen to meet with him and he will come after he 's formed the government - President Clinton , the secretary of state , committed to working closely with the prime minister-elect , to advance the peace process .
the U.S. has played a key role in Israel 's peace talks with Syria .
After Netanyahu 's victory , those talks seemed to be in jeopardy , but now a Netanyahu aide says the prime minister would like to resume negotiations with Syria , albeit with more limited goals .
Analysts say it 's the first clear sign that Netanyahu may try to advance the peace process
Eric Weiner in Jerusalem .
In Alaska , a wildfire has consumed more than 10,000 acres and continues to burn out of control .
The fire is centered in the Matanuska Valley , 30 miles north of Anchorage .
It 's forested country with dirt roads and many homes .
It 's one of the fastest-growing regions in the state .
Hundreds of buildings have burned and more than 1,000 people have been evacuated .
Tom Boatner is a firefighter in Fairbanks who 's been on the scene since Sunday .
We reached him in Houston , Alaska , where the forestry division has set up an incident command post .
We are getting strong winds .
We 've had another wind shift .
We 're getting 20 to 25-mile-an-hour winds with gusts to 35 .
Conditions are dry , so the combination is making for radical fire behavior .
In this part of Alaska , we 're seeing fire behavior that occurs three or four times a century .
Tell me what you mean by radical fire behavior .
This fire is burning through black spruce , white spruce and birch forests .
The top of the canopy of this forest is 60 to 100 feet high , and flames are 100 feet taller than the trees .
The fire is so hot that we ca n't go direct attack , meaning putting people and engines and pumps on the fire line .
It 's too dangerous .
I ca n't imagine you could send people into an area where the column of fire was taller than a 20-story building .
No.
the last 48 hours we 've had one priority and that is , do n't kill anybody .
In 21 years of fire fighting , this is as dangerous a situation as I 've seen .
this fire is rolling through forested country with hundreds of homes scattered through the forest , so firefighters are trying to save people 's homes .
With fire breaks and soaking them down and fire retardant .
Yeah , right .
we 're not able to do anything without water , so all of the structure and protection has been with fire engines .
Fire engines .
Yeah .
the wildland fire engine , and also volunteer fire engines from all over the state .
we 're going to continue prioritizing structure protection , but today we 're going to nail down some perimeter so we can stop it from galloping across the countryside .
Describe how you would do that .
we 're putting out resources on the perimeter that include hand crews , engines , bulldozers , water tenders - supported from the air by helicopters with buckets and retardant bombers .
we try to knock down the flames and the heat on the perimeter and put out the hot spots and secure that perimeter so the fire ca n't advance .
thanks .
You 're welcome .
Tom Boatner is operations sections chief for this fire .
He is a smoke jumper for the Bureau of Land Management in Fairbanks , but he spoke to us from Houston High School in Houston , Alaska .
In Montana at the ranch occupied by the Freemen , a letter by a jailed cult leader may have played a role in the first departures since April .
Brian Jenkins reports on this and other developments on day 75 of the standoff .
He joins us live .
Brian ?
we have a new encouraging development three or four minutes ago .
Two members of the Freemen group on the 960 acre property came to the entrance to meet with two FBI agents who had been there for half an hour .
They had pulled their vehicle down .
It 's the vehicle we have seen many times go that entrance .
They appear to be talking .
About what we do not know .
One of the state legislators who served as an intermediary early in this standoff has said that negotiations could pick up speed now that two girls have been taken off the ranch , a family of four left Thursday .
Gloria Ward , her husband Elwin and two daughters aged 10 and eight .
They were taken first to the FBI command post in Jordan , 30 miles southeast , then to Miles City , where a judge granted temporary custody of the girls to their aunt , and gave jurisdiction over the girls to the state of Utah .
They were taken to Billings .
They flew out of Billings this morning and arrived in Salt Lake City .
If we have that picture , you 'll see Gloria Ward with long , dark hair , her two children- , Courtney , 10 and Jay-Lyn , eight .
Jay-Lyn 's father lives in Utah .
The older girl 's father lives in Salt Lake City , and they have expressed relief that the girls are free .
The girls ' mother belongs to a sect of ex-communicated Mormons , called the House of Cheney , and Gloria Ward 's sister asked the leader , John Cheney , to write a letter encouraging the Wards to come off the ranch .
We have two comments on that .
from the attorney for Lynn Nielsen , Gloria Ward 's sister .
John Cheney had asked God about them coming out and that God said they should come out , that they had work to do outside the ranch .
in a phone interview John Cheney had said he wrote the note , encouraging them to leave .
They made their decision on their own .
He gave this interview from a jail cell in Provo , where he is charged with forcing his daughter to marry a follower .
Gloria Ward 's oldest daughter , now 15 , married John Cheney last year and became pregnant .
She is now in the custody of welfare officials in Michigan .
that is where that situation stands , Gloria Ward and her two daughters now in Utah .
again on the Freemen ranch in Montana .
We have two FBI agents meeting with two members of the Freemen group .
We will report further details when we have them .
Natalie ?
Brian Jenkins in Montana .
Thank you , Brian .
If sex education is a debated topic in a relatively open society , imagine what it 's like in a traditional society like China .
you do n't have to .
Maria Ressa set in on a sex ed class and got a lesson on culture , instead .
Their questions seemed naive .
What do you do if you like a boy who 's older ?
What if a teacher asks embarrassing questions ?
these are questions few feel they can discuss with parents and friends .
This is China 's version of sex education , to help girls and boys deal with the problems of growing up.
In two years , 30,000 students have participated in this course , and it 's caused some controversy .
Teachers are afraid , because in the past we never dealt with questions of sexuality .
China 's education system demands a strict code of behavior from its students .
It 's formal , rote-oriented teaching enforces discipline and respect for authority .
It adds a dose of party politics and communist doctrine .
recent reforms have opened up the country to Western influence in movies , television and music and that sends conflicting messages to kids .
They see these things , and they want to try it for themselves .
they 're too young to handle the consequences .
The class is straightforward .
A teacher addresses the changes going on in their bodies and speaks about topics normally considered taboo .
that encourages students like 14-year-old Chen Jing .
I wish my parents and my other teachers could be like this , so we could communicate .
It 's a conservative society .
Chen has no boyfriend and would not want one until college , but girls in her class face an added problem .
They are one of the first generations of China 's policy which restricts couples to one child .
With no brother or sister to confide in , it becomes difficult to handle their questions of sexuality , and skewed ratios of boys to girls may put additional pressure on them .
Chen says this class is a relief , helping her understand and deal with questions she could n't talk about .
Maria Ressa , CNN , Beijing .
President Clinton left on a three-day campaign swing that could generate controversy .
He 's leaving behind the controversy about FBI files on some well-known Republicans .
Kathleen Koch is at the White House with the latest .
Kathleen .
Good morning , Joie .
the president has left for three days of speeches and fundraising in Nevada , California and New Mexico .
in San Francisco the president is likely to be met with protests from the gay community angry about a bill that would deny federal benefits to same sex couples .
the president would prefer to face that than the furor that has erupted in Washington over the White House 's gathering of 350 people 's FBI files , including some belonging to prominent Republicans in both the Bush and the Reagan administrations .
The White House says it was a mistake that occurred in 1993 when an Army staffer was updating the list of people with clearance to enter the grounds .
Associate White House counsel Mark Fabiani says that that staffer was working from an outdated list , that his replacement discovered the mistake and that there were no more old files then requested .
But Republicans , including Bob Dole , believe there was more to it than that .
everything in this administration is an innocent mistake .
`` We did n't do anything , it was a mistake .
we did n't know it was there .
we did n't know whose fingerprints were on it. ' I think we have to take this seriously .
It 's not good news .
If this had happened in years past , the Democrats are in control , hard to tell what might follow .
I think the president can clear it up if he apologizes to the American people .
White House Chief of Staff Leon Panetta insisted that there was no wrongdoing , it was a mistake , but he still apologized .
nothing was done with that information .
It was not passed on to any officials .
It 's been held within the security office and those files have been returned to the FBI .
A mistake has been made .
It is inexcusable and an apology is owed to those involved .
Panetta says the White House has taken steps to make sure that something like this never happens again .
Nonetheless , FBI director Louis Freeh has ordered a change ordering new restrictions on the sharing of confidential information with the White House .
this change came in a letter to Pennsylvania Republican Congressman William Clinger , who spoke with Freeh Friday about wrongdoing in this controversy .
Joie .
Kathleen , thanks very much .
CNN 's Kathleen Koch at the White House .
to bring you up to date on a story we 've been covering .
In Israel , officials are trying to learn more about a violent incident mid-way between Tel Aviv and Jerusalem .
For the latest on this story , we 're joined on the phone by Jerrold Kessel .
what happened ?
some of the mystery surrounding this shooting is being cleared up .
About 11:15 two people were killed , probably Israeli civilians , in a car .
They were shot dead on a country road 25 miles southwest of Jerusalem .
Police are treating this as a terror attack , but they 're not confirming that as yet .
as to contradictory reports that unknown gunmen had fired bursts of automatic gunfire at a vehicle near an army base 15 miles away from this attack spot , this is being discounted by the police .
they say that , having set up roadblocks , rushed reinforcements to the area , there 's no evidence , no confirmation of any second incident .
But the confirmed shooting attack is being treated as a terror attack .
there 's been no claim of responsibility .
A camera man on the site reports the car halfway in a ditch on the side of the road with 10 bullets through its front wind screen , and that 's why the police are treating it as a terror attack .
The two people found inside were dead , an Israeli couple .
A baby was found in the car unhurt , according to a spokesman for an ambulance rescue service .
Israeli security forces have been on high alert for attacks by Islamic militants during the Israeli election period .
since then , the Islamic militants have vowed to maintain their resistance and to go on attacks after the election of prime minister-elect Benjamin Netanyahu .
the site of the attack is not far from the open border between the West Bank and Israel .
That 's what we know .
Jeanne ?
what measures are authorities taking in response to this incident ?
after the rumors came in , police rushed reinforcements and patrol cars through the area , threw up roadblocks fearing that there was a car with gunmen in it engaging in a shooting spree .
They have set up roadblocks all around this area which is in a triangle between Jerusalem , Tel Aviv , and southwest of that area , in a country district .
They have thrown up roadblocks , but they have not found anything further than that single attack in which the two people have been killed .
they are continuing to search the area to see if there were any further incidents .
No confirmation of anything beyond the single incident .
we will bring you more details on this story as they become available .
we are going to hear from observers of Russian politics about the choice Russians face - whether to extend Boris Yeltsin 's presidency or opt for Gennady Zyuganov 's brand of communism .
British journalist Jonathan Steele says that Yeltsin and Zyuganov appear to campaigning on the same promises .
I think President Yeltsin has stolen a lot of Zyuganov 's clothes over the last weeks and months .
He talks about reviving Russia as a great power , so it 's a more assertive nationalist language than we used to hear from Yeltsin .
he 's talking about spending more to help the poorest sections of society .
He 's talking about subsidizing the military-industrial complex .
He 's talking about controls on imports to protect Russian industry , so this nationalist , protectionist , more state interventionist policy which the Communists advocate is similar to what Yeltsin now says he would do .
do you think that this suggests a lack of conviction on Yeltsin 's part for the policies he has advanced as president , or is it a tactical abandonment of those for the campaign , policies that he would return to if he were re-elected ?
I think it reflects a change in Russian opinion over the last years .
I think there has been a disillusionment with the market economy and a feeling that you have to correct it .
I think what Yeltsin is doing is tactical in the sense that he sees it 's the best way to get votes and get in tune with the Russian opinion , but I think it is something that he would stick to even if he won a second term .
You 're suggesting that the political outlook of Russia 's Communist Party is more in tune with Russia of 1996 than the Yeltsin government over the past years .
on two points certainly .
One is on the economy , and the other is on this sense that Russia has been humiliated over the last five or seven years .
The loss of empire mood , which Russians have got over quickly at the time they were losing the empire in 1990 and '91 , can be seen as a deep-seated wound that has n't healed , and the Communists are talking about patriotism .
They 're talking about Russia having been humiliated and a need to stand on its own feet , even if that means not being pro-Western .
That 's the thing that I think Yeltsin 's taken on board .
the difference is one of speculation about the future- which one of these men would be least likely to tamper with civil liberties and roll back the democratic reforms of the Gorbachev years .
Is Boris Yeltsin a democrat ?
Is he devoted to civil liberties , more so than Zyuganov ?
that is the big debate .
Take television , for example .
All three television channels are controlled by the president .
you could argue that if you want an opposition media , the best thing is to vote Zyuganov , because then all the national TV stations would be against the new president .
that 's an illustration of the fact that Yeltsin has taken into his hands the main broadcast media .
On the question of rights to free assembly , political parties , this has to be speculative .
Zyuganov , who knows that you ca n't go back to one-party rule , that you have to do deals , make coalitions , keep up dialogue with parties that do n't support you - has shown experience and loyalty to parliamentarism .
With Yeltsin , this is questionable .
He has refused to found his own political party or lead one .
He did close down the parliament in 1993 .
He has brought in a very authoritarian constitution which downplays the role of parliament .
the jury has to be out on how much of a democrat Yeltsin is - or Zyuganov - because we know less about Zyuganov .
Jonathan Steele spoke to us from London .
He is an assistant editor of The Guardian .
He is a former Moscow bureau chief and author of Eternal Russia .
Over the past 18 months , churches with African-American congregations have been going up in flames in Texas , North Carolina , South Carolina , Tennessee , Louisiana , Alabama , Mississippi , Virginia , and Georgia .
Clergymen met with officials today to talk about the federal response to these burnings .
investigators are probing another overnight blaze at a black church in Greenville , Texas , while police say that they 've made an arrest in connection with the one that destroyed a church in Charlotte , North Carolina .
Al Hinman joins us now , and has details .
Al ?
their pressure in Charlotte has been great as it is mounting across the Southeast and the country to make sure that arrests are made quickly .
In Charlotte , city-county police officials , state and federal law enforcement agencies felt convinced they could solve this case quickly and that 's what they did .
A comprehensive investigation resulted in a juvenile being charged with setting the fire .
there is no information that any other person is involved or that this incident is connected to any conspiracy .
There is no evidence that this incident was racially motivated .
This juvenile has been served with a petition for violation of burning churches and other buildings , and the suspect is currently being detained .
Two Charlotte-Mecklenberg police officers obtained information through their sources to make the investigation go in the direction of the suspect that was arrested last night .
Additional information was supplied by citizens , and that information helped lead to the quick arrest .
this incident is being said that there is no racial motivation .
There may be other causes involved , but that is not being discussed .
A 13-year-old girl is in custody , a white female .
She has been charged with setting the fire that torched the 93-year-old Matthews-Merkland sanctuary that had not been in use for years .
It has been a loss in this community and members of this congregation and others are working to heal the emotional wounds and move on and show that they can march together , black and white .
Reid ?
All right .
Thank you , Al Hinman live in Charlotte .
You may never see your face on the silver screen , but perhaps your house ought to be in pictures .
Movie studios are on the look-out for the perfect house , finding it 's much cheaper than building a set from scratch .
The homeowners answering that call can be lucrative , but it can also cause headaches .
Fred Katayama reports in today 's Your Money .
location scouts scour neighborhoods for a house with star quality , searching for bigger homes with enough space for equipment plus 100 cast and crew .
A modest house can fetch rental fees of $ 1,000 a day ; a mansion can command a rate of $ 10,000
If your home is chosen , clear away your notions and focus on reality .
It 's hard to understand how all-consuming and huge it is.
Once we go into your home , we 're in every nook and cranny .
The owners of a home used in Mrs. Doubtfire sued the producers , claiming the house was trashed .
before the first frame is shot , nail down a few essentials .
Ask the right questions of what they want to be doing there and when ; and get everything in writing that you can .
insist on a contract that sets out specifics of the shoot , and make sure the studio has insurance covering any damage .
prepare for an invasion .
They started setting up the house around Thanksgiving time , and now it 's June , and they 're still talking about shooting .
Rob Kos ' New Jersey home is being used for The Devil 's Own , starring Harrison Ford and Brad Pitt .
Kos says , despite the commotion , the experience has been worthwhile .
It was an adventure and a once-in-a-lifetime experience to see how movies are made ; so we just rolled with the punches , and it 's been great .
For most homeowners , the dream of stardom is a long shot .
to improve the odds of being discovered , list your home with film commissions and production companies .
That 's Your Money .
Fred Katayama , CNN Financial News , New York .
In California today , the largest seizure of smuggled automatic weapons in American history .
seven people are under arrest , including two Chinese with ties to the Chinese military .
Brian Ross is in San Francisco .
U.S. customs agents had been tracking huge shipments of Chinese weapons into this country , which is what led undercover agents to set up the illegal shipment of 2,000 AK-47's , guns the undercover agents had claimed were destined for American street gangs .
They also negotiated more sophisticated weapons with a comment that if you throw these into a crowd , they can kill many people .
In addition to the seven Chinese business people charged today , at least seven others are being sought .
The Chinese government is into this thing up to their eyeballs .
The case leads back to two prominent arms companies tied to the Chinese Peoples Liberation Army .
One called Poly Technologies , headed by the son-in-law of Chinese leader Deng Xiaoping .
the other , Norinco , which manufactured the AK-47's seized in the government sting .
undercover agents were preparing to lure two high-ranking Chinese officials to San Francisco when the sting had to be ended prematurely .
Brian Ross , ABC News , San Francisco .
In Serbia today , President Slobodan Milosevic has pledged to the United States that within one week Bosnian Serb leader Radovan Karadzic will be removed from power .
Karadzic has been indicted by the War Crimes Tribunal in Holland .
Back in a moment .
Investors on Wall Street this week were quick to pick up Saks Holdings .
The parent company of Saks Fifth Avenue offering a 26 percent stake .
Investors rushed to buy the stock on its first day of trading , ending the week up $ 8 from its initial price of $ 25 .
Luxury is in.
While the retail sector 's recovery has been spotty , the sky 's the limit for high-end stores .
Wall Street is betting that Saks will continue the trend .
The retailer will raise $ 400 million to wipe out more than one-third of its debt .
wealthier consumers are benefiting from economic trends , and they 're spending money and we 've seen that in stores like Tiffany and Gucci , where the results have been better than expected .
Tiffany split its stock after reporting a big jump in quarterly earnings , and Gucci stock soared after reporting a 113 percent jump in revenue .
Designer Donna Karan , sensing a friendly environment towards fashion , is readying another public offering .
the hunt is on for the next hot retailer , and some stores are wondering if they should answer Wall Street 's call .
We 've been sought after .
we are educating ourselves , they are educating themselves about us and when the time comes we make the move .
Heads of private apparel companies worry about ceding control to share holders who may not agree about how to run the business , but with the market conditions so favorable , more are getting over their fear .
Kitty Pilgrim , CNN Financial News , New York .
I declare the Disney Store in Manhattan officially open .
Walt Disney opening its latest store to the public .
The three-story Disney Kingdom is located a block and a half away from Warner Brothers .
Disney paying $ 400 a square foot for the location , but says the publicity is worth the price .
Dan Rutz joined a fitness expert to get advice on how to enjoy exercise without getting hurt .
It 's a flow of injuries .
like most medical experts , Dr. Thomas Branch , of Emory University , believes that the benefits of exercise outweigh the risk of getting hurt .
A workout should start with stretching .
80 percent of your stretch occurs in the first minute .
The cords that bind muscle to bone require special postures .
Muscles stretch best when gradually put to work .
Branch warms up on a stationary bike .
What about a jog or a walk ?
Would that accomplish the same thing ?
That 's the same thing .
OK.
Yep .
Start slow , get the muscles moving , then the jog becomes safer .
three out of four men in the CNN/Men 's Health poll say they 're in good shape , but national statistics find a third are overweight .
Many quit exercising when they get hurt , but proper warmups and not overdoing it can prevent tendinitis , ligamentitis .
An inflammation of a tendon can cause pain when you exercise and become a recurrent pain difficult to get rid of.
What are men in their 30s , 40s , 50s , and 60s doing running ?
What 's the point ?
Why bother ?
exercise for your cardiovascular system to prolong life and to limit disease are the main reasons .
Richard Krebs has a third reason .
He enjoys an active lifestyle even though he 's coming back from an injury that required surgery to repair .
I had an unfortunate occurrence , but know these things happen all the time .
There are other kinds of risks , and I do n't believe in sitting home and playing it safe .
He 's coming along with his muscle strength .
Rehabilitation helps reduce the chance of reinjury , and to avoid trouble in the first place , get to know your body , especially when things do n't feel right .
Once you learn about your body , the next time those symptoms appear you do n't have to go to the doctor .
Let me ask you if we 're trading fitness for 40 for arthritis at 60 ?
you might be doing the opposite .
If you do the right amount of exercise and incorporate cross-training into your program , you may be prolonging your life and reducing arthritis .
Cross training means mixing up the fitness routine .
instead of wearing out one part of the body , all of it will stay fit .
According to the experts , we can either use it or lose it.
Dan Rutz , CNN , Atlanta .
The San Diego Zoo hit the Web this week .
Explore the Gorilla Tropics Habitat , visit Mombassa Lagoon , to see animals like this white alligator or interactive exhibits and be sure to see some baby faces only a mother could love .
For more science stuff take a look at the Why Files .
This page gives you the science behind the news , with topics from Mad Cow disease to comets .
The Cool Science Image area lets you see a butterfly 's nodes and other images from an electron microscope .
And for more science information check out Access Excellence .
This is a page developed by Genintech to help biology teachers understand the biotech industry .
the What 's News area is full of articles about current science issues .
The Resource List is a collection of links to Web sites from NASA to interactive frog dissections .
http://.sandiegozoo.org
http://.whyfiles.news.wisc.edu
http://.gene.com/ae
When looking for a place to live some people insist on a lot of closet space , others wo n't take an apartment without a great kitchen .
on New York 's lower east side computer connoisseurs look for something different .
Norma Quarles has the story .
This new five story building in the east village is in a community known for tenements and squatters than for high rent apartments .
this building has something computer users want and are willing to pay for : a T1 cable giving them high speed access to the Internet .
this is the first building that has been wired with T1 cable access to the Internet from its inception .
Josh Kilmer Purcell pays $ 1550 a month for a one-bedroom apartment and $ 85 a month for the service .
it has to do with speed .
I can work from here , with my office in New York , as well as the office in Atlanta .
I can do my layouts on my designs here .
if I have an idea I can retrieve files from either of those offices .
As far as convenience , it 's invaluable .
they could charge more and I would still pay .
John Brann , is a chief technologist for a software company .
I 've been a regular Internet user for three years , both at work and at home and even the ordinary things with simple graphics on the Net can take ages to download through an ordinary phone line .
Apartments range from $ 1500 to $ 3500 a month .
The building just opened and 25 of the 28 units are already rented .
the fact that the building is wired and is set up for the wide band access is something that I am prepared to pay for .
NetGuide magazine says this may not be for the average computer user .
Not everyone needs a lot of band width and most people can do with a 2400 baud modem and a phone line .
we are seeing a combination of New York real estate hype and Internet hype but if people are willing to pay they must believe it is worth it.
Norma Quarles , CNN , New York .
any do it yourselfer will tell you that home improvement projects come in two kinds - success stories and unmitigated disasters .
we will show you new CD ROMs , that can help ensure that your next repair job does n't turn into a money pit .
We will be back .
On World News Tonight , the first break in months at the Freemen ranch in Montana .
A family of four leaves ; the wildfire in Alaska spreads ; and elsewhere in America , interfering with Mother Nature to make the problem worse .
These forests are going to burn .
Senator Dole on abortion .
He would like the Republican platform language to change .
this is World News Tonight with Peter Jennings .
Good evening .
We begin in eastern Montana .
There has been a change in the status quo .
A family of four has left the compound where the Freemen of Montana have been holed up.
They are the first to leave since April .
they leave after a week in which the FBI has increased the pressure on the Freemen , who have been holed up on their ranch for more than 10 weeks .
Ron Claiborne on who comes out and who stays .
They left this afternoon , meeting two FBI agents on the road leading to the compound .
The departure follows a discussion between the agents and those inside the vehicle .
Inside the car were Elwin Ward , his wife Gloria and her daughters - 10-year-old Courtney and 8-year-old Jay Lynn .
Gloria Ward had been facing a felony charge in Utah for denying visitation rights to the father of one of the girls .
authorities had agreed to drop the charges .
It is not clear why the family chose or was now allowed to leave .
this week , the FBI cut off electricity to the compound .
Today 's departures may signal that the increasing pressure and new negotiations may pay off.
with 17 people still in the compound , including its leaders , there is no indication that the standoff is about to end.
Ron Claiborne , ABC News , Jordan , Montana .
home video preview with Dennis Michael .
Grumpier Old Men is out on tape .
we do n't want to comment on that
Nicolas Cage 's character has come to Las Vegas to drink himself to death , but he falls in love .
Leaving Las Vegas is one of the darkest romances to dance across the screen , but a best actor performance by Cage and a brilliant turn by Elizabeth Shue make this tale irresistible .
Not for kids , grownups should n't miss it.
Grumpier Old Men is n't as good as the original , but that hardly matters since Jack Lemmon and Walter Matthau are walking encyclopedias of comedy and the story line hardly matters either , except that it brings Sophia Loren into the mix .
a comedy that lives for the moment .
this movie 's moment passed , but it 's only now coming to video .
Heavy Metal was named after the magazine that inspired it , but it looks like somebody tried to make a movie out of old album covers .
rarely does this flick take flight .
Collectors only .
See you at the rental counter .
Dennis Michael , CNN Entertainment News , Hollywood .
Democrats accused Robert Dole of breaking election law by overspending in his campaign .
In April , the campaign came close to the $ 37 million limit Dole promised to abide by , in exchange for taking federal matching funds .
Democrats charge he exceeded the limit in May .
NPR 's Peter Overby reports .
The Dole campaign spent heavily to build a sense of inevitability around his candidacy .
When Pat Buchanan and Steve Forbes made the race more competitive , Dole had to keep on spending .
Dole knew the rules when he decided to run .
He made the decisions to spend at a high rate .
He made those decisions on his own .
He expended most of his money , and the fact that he 's out of money and being forced to violate the law is his responsibility .
In a complaint filed at the Federal Election Commission , the DNC focuses on Dole 's spending from May 1st to the GOP convention in August .
After the convention , both Dole and Clinton will get $ 62 million for the fall campaign , but until then Dole is out of money .
For of May , we determined the costs that the Dole campaign must have spent , based on past patterns , as reflected in their FEC reports and press accounts of campaign operations .
The Democrats released spreadsheets and other documents to support their charges that the campaign is $ 343,000 over the limit , that the Republican National Committee and other organizations are secretly paying for campaign activities and that there 's no way Dole can get through the convention without going over the limit by a million dollars .
Dole denied that his campaign has overspent or broken any laws .
He said Clinton is getting undisclosed support from organized labor , and that Clinton did n't have primary challengers .
But he got a $ 10 million subsidy for taxpayers for his campaign without opposition .
And then organized labor laid down 35 million bucks .
Here 's 35 million . '
Dole got reinforcements from the Republican National Committee .
Chairman Haley Barbour called a news conference right after the Democrats held theirs .
It is a tactic of the left to try to win in court what you ca n't win at the ballot box .
This is a transparent attempt by Clinton and the Democrat Party to try to divert attention away from the bad news about their own legal and ethical problems .
Barbour released numbers from the Dole campaign .
It started out at the same point the Democrats did but listed income that the Democrats did n't include .
it would come from selling assets of Dole 's primary campaign to the general election campaign .
Barbour said campaign spending ought to be deregulated .
We 've got a law that 's unfair .
we 're in a situation where Clinton had $ 20 million to spend for his general election .
He 's got to spend it for general election purposes prior to August the 29th .
Dole , because he had to win his party 's primary , has a million dollars .
That is unfair .
It is a stupid law .
The American people want competitive politics .
The Democrats are asking for action from the Federal Election Commission , but that moves slowly .
the FEC fined House Democratic leader Richard Gephardt for violations by his 1988 presidential campaign .
He paid in 1995 .
I 'm Peter Overby in Washington .
Bob Dole is catching flack from another angle- the Democratic National Committee today charged he has played fast and loose with primary campaing spending limits .
The Dole camp denies it.
Brooks Jackson has the story and a bit of political history .
Democrats say Dole is flunking civics .
Democratic National Committee Chairman Don Fowler accused Dole 's campaign of violating pre-nomination spending limits by $ 343,000 and said the Federal Election Commission should step in to keep the total from going higher , and he attacked Dole 's personal character .
This is about trust .
Bob Dole pledged that in return for millions of taxpayer dollars , he would obey the law .
He has broken that promise , and he has violated that trust .
a look at the history of similar complaints shows this sword can cut both ways .
Clinton 's 1992 campaign was accused of gouging taxpayers .
Clinton 's campaign got federal funds , ostensibly for his primary campaign , based on contributions received after he was nominated .
FEC auditors wanted Clinton to repay $ 4 million ; it would have been the most ever .
the three Democratic commissioners vetoed that .
The FEC deadlocked on partisan lines .
The Clinton campaign has never been found guilty of any violations of the Federal Election Campaign Act or paid one penny in penalties .
No civil penalties , but the Clinton campaign repaid taxpayers more than $ 1.3 million .
how about House Democratic leader Richard Gephardt ?
his 1988 campaign went over the limit in Iowa by more than $ 450,000 , 60 percent higher than allowed .
He had to give back $ 120,000 .
Candidates have been overspending since limits were enacted .
Ronald Reagan went $ 30,000 over the limit in New Hampshire in 1976 , and $ 55,000 over in 1980 .
in 1980 , Jimmy Carter overspent in Iowa , New Hampshire , and Maine .
Ted Kennedy also broke the limits in Iowa and New Hampshire .
Limit-busting has n't worked well as a campaign issue .
In 1984 , Gary Hart attacked Walter Mondale for using delegate committees to evade limits .
He must give the money back .
Give the money back , Walter .
Hart lost , even though he was right .
Mondale eventually paid $ 350,000 to settle the findings of illegality .
Democratic Senator John Glenn 's opponents keep bringing up $ 2 million in bank loans to his '84 campaign , loans the FEC said were illegal .
People are still waiting for their money !
John Glenn - he just keeps owing .
Glenn won that '92 campaign and those loans are still not paid off.
the Dole campaign denied overspending , and Dole pointed to Clinton 's use of leftover primary funds .
I 'm concerned about Clinton getting $ 11 million from the FEC when he did n't have an opponent in the primary .
he ought to refund the $ 11 million .
However Dole 's spending plays out as a political issue , do n't expect a legal decision soon .
George Bush violated the primary spending limits in 1988 , and it took the FEC until last December to close the case , with a letter telling the ex-president , do n't do it again .
the ball could be on its last bounce tonight for the NBA season .
The Chicago Bulls and Seattle Supersonics are facing off.
Chicago could take its fourth championship of the decade with one more win .
Jeff Flock joins us now and is bracing for a wild night on the streets of Chicago .
Jeff , how you doing ?
it is a wild night .
This is Michael Jordan 's Restaurant and , as a Bulls birthday cake passes over my head in just about two seconds - - but not good news for the Bulls so far .
they are trailing the Seattle Supersonics by 21 points at halftime , so it 's appropriate for us to show you Michael Jordan 's Restaurant .
Perhaps you see the picture of Michael , as it soars two or three stories over Chicago painted on that restaurant .
this city concerned if the Bulls can claim victory tonight , concerned that they do n't have a repeat of what happened in 1992 .
That is when the Bulls won their second NBA championship of three in a row - a lot of problems on the streets when they clinched that NBA title - looting , cars were overturned , things got out of hand .
So the city has made a concerted effort , spending upwards of $ 3 million on security and putting together a public service announcement , featuring Bulls coach Phil Jackson , Michael Jordan himself and an unlikely candidate for a public service announcement on how to conduct oneself properly - Dennis Rodman .
like last time , we 're all in this together .
If we win , celebrate our achievements with style and dignity .
This Chicago 's moment to shine .
Let 's show the world how to do it right .
they hope the Bulls clinch the championship - however at this moment , things not looking well , the Bulls down by about 20 points .
We will stand here and dance with the folks and hope that things turn out for the best .
We 'll watch it.
live from Michael Jordan 's Restaurant in Chicago , Jeff Flock .
Back to you .
Bob Dole 's first day as private citizen and presidential candidate may not be all he had hoped .
his Senate exit yesterday left him with a `` empty feeling , ' reinforced today .
That did n't distract Dole from courting voters in Ohio and projecting the attitude of both a regular guy and a winner .
Marc Watts is with the Dole camp .
The first order of business for Dole - changing the name of his campaign plane to Citizen 's Ship .
Until yesterday , it was called The Leader 's Ship .
the former Senate majority leader embarked on his first campaign trip as a private citizen .
First stop - Toledo , Ohio .
George Strait 's song `` Heartland ' welcomed Dole at a luncheon for the Toledo Chamber of Commerce .
America 's Heartland is the theme of the campaign trip .
I 'm going around the country to see where they have the best unemployment benefits and I thought I 'd check it out in Ohio and then go to Kansas .
His speech was an extension of his farewell remarks before Congress , but today the tone was more partisan .
I 'm not going to run on a stolen agenda ; it 's going to be my agenda .
It 's not going to be the House or the Senate agenda , it 's going to be my agenda for America and for the future .
I do n't have any personal animus towards President Clinton .
he called me yesterday , and I 'm going to call him November 5 .
Dole reflected on his years in Congress , promising he 'll run for president with the same commitment he brought to the Senate .
Running for president is a full-time job , and I 'm going to have the time I need to focus and to get the job done .
this trip is a chance for Dole to showcase himself as a regular person .
he 'll travel to Kansas to return to his roots there , and he 'll be more open and engaging as the campaign continues .
The former Senate majority leader will visit eight states in three days , and he 'll return to Ohio several times before the election because it 's an important swing state .
I 'm determined to criss-cross America and tell our story .
Not only is Ohio an important battleground , but it knows something about picking winners .
Only twice in the past 100 years has Ohio not selected the winner , and no Republican has ever won the White House without winning Ohio .
Marc Watts , CNN , Toledo , Ohio .
a DC-10 with 275 people on board crashed today after takeoff in Fukuoka , Japan .
three people are dead , dozens more are injured .
Garuda Airlines Flight 865 was en route to Jakarta , Indonesia .
Tom Mintier joins us by telephone in Tokyo .
Tom , what can you tell us ?
What 's the latest ?
the latest is that three people are dead .
The amount of people hospitalized has risen to 100 and 12 are missing .
Part of the fuselage is too hot for investigators to enter , and there is a fear that the death toll may climb - that many of those missing are trapped in the fuselage , in the part that has burned .
Garuda Indonesia Flight 865 was airborne for minutes , lifted off the runway only a few meters before slamming back down .
There is a possibility that engine problems attributed to this crash .
flames could be seen coming from the aircraft before the impact .
The Fukuoka International Airport is 2,000 meters long .
Most international airports that service large planes are 4,000 meters , and it may be a contributing factor .
The pilot had reached that point where he began his lift-off and that was when the problems began .
rescue crews were on the scene within minutes and conducted the rescues and the firefighting simultaneously .
Many people were able to slide down the emergency chutes .
There was criticism of the stewardesses , saying that they did not guide them and conduct emergency evacuation procedures properly .
these are the passengers who were on board the plane , saying they were indicated to go out exits that were on fire .
the investigation will not only center around the cause , but the action of the employees of the flight .
three people are listed as dead , 12 are missing , and more than 100 are hospitalized in after this plane crash .
do we have any information on the history of this aircraft and its safety ?
We do n't have any information about this individual aircraft .
The DC-10 has had problems with engine failures before .
There are going to be parts of the investigation looking at that .
There was a hole in engine number two , which is mounted on the tail .
This is not a part that burned , but a huge hole could be seen and experts have not been able to explain why that hole is there .
It 's possible that one of the turbines cut loose and ripped through the fuselage , but it 's something that investigators will have to take a look at.
experts say they are puzzled by this crash .
What about weather ?
Has that been ruled out as being a factor ?
Airport officials say that it was overcast , but not a problem .
during the rundown of the runway the tower asked the captain to change radio frequencies , but the captain did not respond .
Apparently , he was already having trouble at that time controlling the aircraft .
Tom Mintier , from Tokyo , Japan .
Thanks , Tom .
Stay with CNN as we continue to look into this story .
Andrea ?
Our political analyst is in the Washington studio .
aside from the legal concerns , what kind of problem is this for the administration ?
this Whitewater committee is dominated by Republicans .
It 's a partisan committee .
the report that Bob [ Franken ] was describing is being prepared by the Republican majority in this committee .
the voters will recognize that this is a partisan document .
more serious were the convictions of several associates of the Clintons ' - James and Susan McDougal , the governor of Arkansas , Jim Guy Tucker - which was done , not by a partisan committee but by a jury of citizens in Arkansas .
that would create more damage .
this does focus the public 's attention on mysterious , unexplained behavior by the White House .
No smoking gun here , but a lot of questions .
most Americans have concluded the White House must be hiding something .
The disappearance of the Rose Law Firm billing records , the handling of the Foster documents after Mr. Foster 's suicide , the FBI records that were taken by the White House for no reason , the contacts between the White House and the Treasury Department .
those things suggest to voters that the White House is hiding something .
What are the political considerations for the Republicans on this committee in writing this report ?
They 've got to be careful about how they handle the first lady in this report .
that 's the debate they 're having right now .
Whether they name her or hold her culpable- it ratchets up the investigation to a higher level because then the Republicans are taking on the first lady directly , and that becomes a far more serious matter .
It makes it more serious and more political .
OK.
Bill Schneider in Washington , Bob Franken in Washington .
It sounds like you both have a cold .
We hope you get better over the weekend .
It 's not easy to figure out what 's going on in the brain of an infant .
researchers say there is more happening in there than previously thought .
Lisa Price explains in tonight 's News From Medicine .
Born prematurely , Kara is 38 days old.
her mother is helping her fight stress .
It 's no joke .
studies show the same emotions and environmental factors which influence adults also influence infants .
Research by the Families and Work Institute suggest brains develop earlier than previously thought .
this new knowledge has overwhelming cultural ramifications .
Kids attending this day care center are receiving the attention they need .
those who do n't may been impaired , socially and emotionally .
I do n't care what you do .
I do n't care if you take your money and dedicate it to treatment .
You ca n't build in things that did n't grow in the first five years of life .
Touch , eye contact , sensory stimulation help the brain to grow .
The evidence is in.
Scientists have looked at this issue about the first years of life .
They 've looked in the uterus and they know that this is the building block that will determine the success or failure later in life .
Scientists say we 're seeing more tragic examples of these kinds of failures .
Surges in crime , where children feel little or no remorse about what they 've done .
They do n't have remorse .
They regret that they got caught .
Regret is an intellectual response .
Remorse is an affective , emotional response .
They do n't have that .
the irony , is that those most important first years are the ones given the least attention .
It 's a culturally foolish thing .
Lisa Price , CNN , Chicago .
more on the Russian presidential elections - a run-off appears certain between President Boris Yeltsin and Communist Party leader Gennady Zyuganov .
the stakes are high for Russia and the rest of the world .
Let 's check in with Ralph Begleiter , who joins us from Moscow with the latest .
Ralph ?
Boris Yeltsin is edging out Gennady Zyuganov in the first round of the election , but not by enough to avoid a runoff .
With 50 percent , more than half of the votes counted now , Yeltsin leads Zyuganov by 3 points .
The third-place candidate is retired Army General Alexander Lebed , who has enough votes to make him a desirable target for political bargaining , which already beginning in Moscow .
On Russian television , which has ignored everyone but Mr. Yeltsin in the past weeks , Lebed appeared for an interview .
Lebed implied that he would begin military reforms tomorrow if Yeltsin appoints him to a government post .
I have program for the reform , and I need power .
If I get authority I will look up to the expectations .
Lebed conceded that his time has not yet come to be president .
skeptics have speculated that Yeltsin might approve fraud to guarantee a victory .
More than 1,000 international observers have been watching the election .
One of them is former U.S. Central Intelligence Agency director James Woolsey , who once inspected Russia through spy satellites .
I asked Woolsey about his observations at the polling places he visited .
The town of Klim , where our group from the Jamestown Foundation was today , things appeared to be going well .
It was stirring and touching .
The balloting was taking place near where the Russians had stopped the Nazis in their invasion of World War II .
maybe Hitler and Stalin were turning over in their graves to see a free election in Russia with precinct captains and people coming in to the polls , flowers in front of the constitution in celebration .
It was nice .
was there an opportunity for cheating in the way the votes were being sealed ?
The procedure seemed simple and effective .
One ca n't tell about the voting lists , and about what might happen in some central location .
the fact that this is paper ballots and paper counting would suggest that if something were done to adjust the results , it would be straight forward to check up on it.
people seemed to be taking this seriously
They were coming to the polls dressed up.
They seemed to be serious about filling out their ballots .
Tell us what you observed .
Exactly .
They were happy .
There were differences .
We did some informal exit polling and found a large number of votes for Yeltsin and a smattering for other candidates .
people felt as if they could speak up and say what they thought .
say what they thought they did .
with 58 percent of the paper ballot counted , Boris Yeltsin leads Gennady Zyuganov by 35 percent to 32 percent , and Russia is poised for a runoff election between Mr. Yeltsin and Mr. Zyuganov , in two or three weeks .
Jill , Martin ?
OK , thank you , Ralph .
Boris Yeltsin has won the most votes in Russia 's presidential election , watched around the world .
because failed to win a majority , Yeltsin will face Communist candidate Gennady Zyuganov in a runoff next month .
Yeltsin captured 35 percent of the vote and Zyuganov nearly 32 .
Former Soviet Army General Alexander Lebed finished third with 15 percent .
Democracy is new to Russia , but Russian voters appear to have sized up the candidates as voters in the West do , and the biggest issues were the economy and character .
CNN 's Claire Shipman reports from Moscow .
The Special Edition churns out what most Russians had expected - round two , Yeltsin and Zyuganov .
to Viktor Skyorastan , Yeltsin 's lead was disappointing .
He is a Zyuganov man .
Yeltsin promises a lot , but never comes through .
his wages have dropped in the last five years .
He ca n't afford to take his family on a holiday .
polls show that Russians cast their ballots based on their pocketbooks .
Chechnya , even crime , paled by comparison .
Oxsuna and Amaryna gambled on Yeltsin and will again .
My life is better .
It 's not that I like him , but I do n't think it will get worse with him .
Lets leave things the same .
The support for General Alexander Lebed seemed to reflect an desire for order .
We 've had the dictators and now the bandits .
We need a normal , trustworthy person .
life is hard enough without the instability and worry about tomorrow .
Russians took the election results in stride , hardly surprised and not looking forward to another politically charged few weeks .
Thirty percent of the population did n't vote .
What would I vote for ?
I 'm a pensioner .
I live below the poverty line .
more than a million Russians - 1,142,000 - did vote for the uncandidate .
Mr. None of the Above came in in sixth on the ballot of 10 candidates .
Claire Shipman , CNN , Moscow .
Federal agents , state lawmakers , and others tried to keep the Freemen talking through their 81-day standoff .
The content of those talks was kept secret , but a Colorado legislator gave CNN an inside glimpse .
Weeks before the 16 Freemen walked off their ranch and into custody , their anger and threats spilled over in negotiations .
You 're going to save my life by imprisoning me ?
Colorado State Senator Charles Duke recorded his mediation efforts .
In a room with 12 armed Freemen , he listened as they called government officials citizen prostitutes who had no jurisdiction over them .
I did n't stand up for this country to have a bunch of prostitutes put people out of here on their ass.
they can take their warrants and shove them up their [ expletive deleted ] where that 30.06 is going to drill 'em .
Russ Landers is getting agitated and I 'm not sure but at some minute he 's going to say , `` you 're one of them , ' and whip out his gun and plug me- I do n't think he would do that , but the possibility is there .
On May 21 , the negotiations broke off.
When Duke failed to mediate a settlement , he placed the blame on the Freemen , saying many of them were not idealists , but criminals trying to avoid prosecution .
With the talks over , the Freemen resumed their armed patrols , but Freeman Edwin Clark became a key force inside the ranch .
Duke and the FBI had tried to convince Clark to be a leader and counter the actions of other Freemen , but Clark agonized .
He did n't want violence , but did n't want to turn people over , either .
The day the mediations failed , Clark told Duke over he was near despair .
I 've got little faith left in me , and when I give up is when things goes to hell in a handbasket .
It created a great deal of stress on him .
He was n't comfortable with that role , and it took a couple of weeks for him to assert himself .
the turning point came when the Ward family and their two girls left the ranch on June 6 .
success convinced Clark to press the others to surrender .
On June 14 , they did .
Jim Hill , CNN , Monument , Colorado .
political contests are heating up as the election approaches ; and added to the mix of normal election year politics are factors including Whitewater , a scandal over the use of the FBI by the White House to uncover information about Republican rivals , and a lot more .
The result is a stronger showing in the polls for Bob Dole .
Joining me to put some perspective on what is going on in Washington , Steve Bell , the head of the Steve Bell Group .
He joins us every Monday .
Steve , good to have you with us.
Glad to be here .
the latest polls and indicate that Clinton 's lead over Dole has narrowed to single digits .
What 's going on ?
we have to be careful about polls this far from the election , but three or four weeks ago the president 's momentum slowed drastically .
It was n't just the Whitewater investigation and the convictions that Special Prosecutor Ken Starr got in Arkansas .
It was also claiming the Soldiers and Sailors Act and active duty and of things like that .
Dole got a boost by leaving the Senate ; and the FBI files used by the White House and sent back have drawn criticism from Lou Freeh , the head of the FBI .
this is another factor of what will be an interesting report when released tomorrow by the Whitewater committee of Congress .
the Whitewater report indicates criminal charges should be considered for some senior administration officials .
Have you heard anything to that effect ?
yes .
The rumors are rampant , with some of the document leaked , that two or three members of the White House staff might be recommended for prosecution .
there 's this notion that perhaps Hillary Rodham Clinton would be indicted if the allegations in this report are true .
Do you believe that , or are you skeptical ?
you just do n't know .
It 's unprecedented , and much of this has been coming out in dribs and drabs that it 's just hard to tell .
between this and the FBI files and the next round of the trials on Whitewater , the White House is going to be doing more legal work than campaign work .
Whitewater 's been one problem for the presidency .
The other one , reports about the FBI search of people 's records , including those of past Republican officials .
Which one 's hurting the president more ?
I think you 're going to see more damage from the files and the FBI information that the White House retained .
This is a breach that smells
All right .
we have lost the ability to hear Steve and we will have to live without knowing his answer to that particular question , but it does n't matter , because the president 's having a difficult time in the polls anyway .
We 'll have Steve back next Monday to bring us more information .
The Clinton administration is going to expand funding for the Brownfield Project , designed to spur investment in abandoned industrial sites .
Commentator John Chambers applauds the move .
For years , I have practiced environmental law in Washington , D.C.
My practice has taken me from Congress to EPA 's headquarters and into the federal courts that decide the validity of EPA 's interpretation of its congressional mandates .
In carrying out its role as protector of the environment , EPA dances to Congress ' tune .
it is surprising that EPA would undertake a new program as part of its brownfields action agenda .
`` Brownfields ' is used to refer to industrial sites that are no longer in use due to environmental problems .
They take the form of abandoned warehouses , factories or vacant lots .
Those who live or work in cities pass by them daily .
The Government Accounting Office estimates that there are more than 450,000 brownfield sites across the country .
Many of these sites are located in inner city communities where the population is composed of poor and working class minority groups .
The idea is to develop solutions to the problems of blight caused by environmental policies that discouraged investment in areas that had been hurt by contaminants .
In addition to providing money for pilots , EPA set about the task of revising and clarifying its environmental clean-up and liability guidance to encourage buyers , lenders and developers to become involved in brownfield projects .
It spearheaded changes to the regulations implementing the Community Reinvestment Act to encourage participation by financial institutions .
The Clinton administration unveiled a means to encourage brownfields redevelopment in the form of a tax incentive proposal .
15 years of as an environmental lawyer has taught me many things .
our lack of appreciation for the environment in the past has caused many of the problems we have today .
excessive regulation has impeded progress that might have been undertaken voluntarily .
EPA 's agenda creates incentives to do the right thing , not only for the environment , but for people hurt by the economic conditions that prevail in many of poor communities .
It is time for Congress to get into the act by providing funding for solving the problem of urban blight .
If legislation is passed to help carry out brownfields redevelopment initiatives , it will be one of those occasions when Congress has elected to dance to EPA 's tune .
John Chambers , an environmental lawyer in Washington , D.C.
Senator Bob Dole ignored the Whitewater and FBI files as he spent a second day courting California voters .
Dole 's strategy in the Golden State appears to be classic , as in the best Republican office is promoting a stronger defense .
This Lockheed plant in Sunnyvale is working on the THAD missile , a more sophisticated version of the Patriot anti-missile used in the Gulf War .
But employment is down to 10,000 , compared with 25,000 in 1986 .
Dole accused President Clinton of dragging his feet on missile defense .
Mr. Clintons opposition to a missile defense is one of the most negligent , short-sighted , irresponsible and catastrophic policies in history .
Dole said it encourages terrorists to think about missile attacks .
From Libya to Iraq to Iran to North Korea and elsewhere , terrorists and anti-American regimes are being encouraged by the administration 's attitude .
Dole would speed development of this plant 's THAD and of missile defense in general .
He noted that people do n't believe what politicians say and linked that with his decision to leave the Senate .
I could put my career on the line , because America 's future 's on the line .
That 's how important it is.
I rolled the dice , and now it 's up to you .
Crowd reactions ?
Here are a few taken at random .
The guy has ideas .
I think that 's part of the problem with politicians today .
They want to be president , but they do n't have an idea what they want to do when they get there .
He 's down to earth and true to what the American people want .
They want to have security .
Dole stopped to visit a volunteer fire station , noting that both his father and grandfather had been firefighters .
Dole used this to say that Clinton 's defense policies have hurt California .
At other stops , he 'll say other Clinton policies have done the same thing in other areas .
From here he goes to talk about agriculture .
Bruce Morton , CNN , Sunnyvale , California .
an F-18 fighter has crashed and burned 25 miles northeast of St. Louis , Missouri , operated by McDonnell Douglas , the manufacturer of the aircraft .
we turn to the Pentagon and Jamie McIntyre .
what do you have there ?
little information at this point , although Pentagon sources tell us this was not a military plane - it was an older F-18 that had been used by the Navy , but was now being leased back to McDonnell Douglas , who was using it for its own purposes .
Pentagon sources tell us that the pilot of the plane , whose fate we still do n't know , was a McDonnell Douglas test pilot , not a military pilot .
sources confirm that they 've heard reports that the F-18 crashed in a residential area in the town of Bethalto , Illinois and that- St. Louis is the headquarters of McDonnell Douglas , where the F-18 is manufactured .
McDonnell Douglas is working on a new , improved F-18 model .
This was not one of those EF models - this was an older C model plane .
we 're waiting for details on whether the pilot escaped injury , and whether anyone was hurt on the ground .
Miles ?
they were trying to test out some kind of retro-fitting to this model .
Do we know anything about those tests ?
I do n't at this point .
We 've made inquiries to McDonnell Douglas .
We called several times , and they have not been willing to talk to us.
they say they 'll have to get back to us.
All right .
Jamie McIntyre at the Pentagon - thanks for the details on that .
And we will continue to keep you posted on this story .
Dr. Jack Kevorkian has attended the 31st suicide .
joining us by telephone is Geoffrey Fieger , Dr. Kevorkian 's attorney .
Mr. Fieger , are you with us ?
Yes , I am.
Thank you for joining us.
Sure .
can you confirm that Dr. Kevorkian was present at this suicide ?
Yes .
Dr. Kevorkian and other physicians assisted Betty Lou Hamilton end her suffering from a disease that was destroying her spinal cord .
Can you tell us more about Ms. Hamilton ?
Who was she ?
She was 67-year-old woman who had suffered from springo mayalia , which destroys the spinal cord .
She described it as having hundreds or thousands of ice picks tearing into her body .
She was treated at the Ohio State University pain clinic .
It is incurable , and she has been counseling with Dr. Kevorkian for six months .
can you tell us how long Ms. Hamilton had been in contact with Dr. Kevorkian ?
six months .
OK.
where was the body found ?
It was n't found anywhere .
It was brought by her friend to the Pontiac Osteopathic Hospital , where doctors confirmed the death and treated the family with dignity and respect and compassion .
thank you for joining us.
We 've been speaking with Dr. Jack Kevorkian 's attorney .
The abortion issue is divisive for Republicans in Texas .
the party there is headed for a showdown at the state convention .
the outcome will determine who will help to choose the party 's nominee this August .
Texas anti-abortion activists have taken a stand and drawn a line in the sand on the state Republican Party 's position .
This convention has decided to say , `` We 're not sending pro-aborts to San Diego to change our platform .
the problem they face is Texas Senator Kay Bailey Hutchison .
a tolerance provision is important for the Republican Party .
That has some Republicans wanting to block Hutchison out of the national convention .
She should be pushed out .
I agree with that .
If she 's not for the family , that 's what we 're here for .
Delegates were asked to sign this pledge by anti-abortion advocates seeking to send their own delegates to San Diego .
Hutchison has received a vote of confidence from Texas senator Phil Gramm who says , if Hutchison does n't go , neither will he .
we have heard from a minority , and they 're bullies .
Bill Price , head of the Texans United for Life , has spearheaded the fight against Hutchison .
Price says if Gramm does n't go , some in the party wo n't mind .
he should buy a white pickup and drive around Texas during the convention .
Anti-abortion activists in other states have had success in getting their own delegates to the national convention .
Hutchison could be the highest-ranking official to be shut out .
State party elders are pleading for unity .
We 've got differences , and I want to help mediate that dispute and see if we can come out united for November .
Texas Governor George W. Bush says he wo n't tolerate a fight or an embarrassment of keeping Hutchison out .
There is no compromise as far as Kay Hutchison goes .
She ought to be a delegate to the convention .
Hutchison 's following here may think Kay is OK , but the controversy is n't the start the state Republicans wanted .
Hutchison did receive a warm welcome from the crowd here .
some delegates say , since Bob Dole made his plea for tolerance on the issue in the Republican Party , the stakes for them are higher .
Paul Caron , CNN , San Antonio , Texas .
A royal update from the insider columnist for People magazine .
Hi , Mitchell .
Princess Diana is a woman who knows how to get the most out of a photo opportunity .
last week Di visited Chicago .
accident the men she danced with were her height or taller .
Di 's partners had to be pre-approved , meaning if anyone was shorter , they did not make the cut .
the Duchess of York was in Los Angeles last week and visited some studios to have meetings involving TV projects .
Fergie wants to have a career in television .
speaking of the Four Seasons , Arnold Schwarzenegger did n't make a lot of friends there this past weekend during the press junket for Eraser .
The junket was held at the Four Seasons and when Schwarzenegger was n't busy boasting about himself to the journalists , he was condescending to the people who are paid to follow him around .
Eraser opens June 21st .
it 's the funniest thing in the world that Steven Spielberg will not be going on the $ 110 million Jurassic Park attraction when the ride has its press preview at Universal Studios Hollywood .
Although the attraction was designed to his specifications , Spielberg gets queasy around thrill rides , especially Jurassic Park , which climaxes with a drop of 84 feet into water .
I ca n't blame Steven for not wanting to go on.
I 'm getting queasy reporting it.
I 'm with you .
yesterday we reported that Jim Carrey went to The Cable Guy premier with his old girlfriend Lauren Holly .
What are you hearing about their reunion ?
they did go together .
they were broken up for a while , but this is a difficult time for Jim Carrey .
less than a year ago Jim Carrey was catapulted into fame , he 's getting $ 20 million for Cable Guy and with a budget that 's probably only twice that , Carrey is hearing negative stories about Cable Guy .
There 's been a negative buzz about this movie .
it opens tomorrow , so we 'll see .
I do n't think he wants to be alone .
This is not a good time for him to be alone .
Who better than Lauren Holly to be with him ?
Good enough .
Thanks Mitchell .
We will see you next week .
All right .
Okay .
we 'll see the rest of you after this .
Do n't go away .
Thank you , Gillian Findlay , reporting from Moscow .
The fallout of this election will not just be felt within the borders .
There are some serious poll-watchers in Washington , hoping their man will win .
ABC 's David Ensor explains .
The possibility of a victory by the Communist candidate sends shivers not only through Yeltsin 's Kremlin , but through Clinton 's White House , too .
A Communist victory would be bad in an election year .
The question from the Republicans would be `` Who lost Russia ? '
The message sent by a Communist victory that will be hard to erase is they did n't get it right , and now there 's a new problem for U.S. foreign policy .
the top expert on Russia , deputy secretary of state Strobe Talbott , says there are contingency plans in case of a Communist win , and that if they abandon reform , the U.S. would stop supporting Russia .
I 'm sure that Clinton will be able to drive home the point that his administration is prepared for any outcome .
Even if Yeltsin does win , policy towards Russia will be an issue in the U.S. presidential race .
For too long , Clinton has delayed action on enlarging NATO , putting the threats of Russian nationalists before the aspirations of democratic countries .
there 's too much of a tendency to identify the future of Russia with one particular Russian leader .
U.S. officials always saw Yeltsin as imperfect .
he drank on the job , ignored corruption , and took the advice to launch in Chechnya a disastrous war .
But with his ratings in the single digits , Yeltsin sprang into action and impressed Russians with an energetic , skillful campaign .
Two months ago I was in panic .
Now we 're thinking about the future .
everything could happen in our most unpredictable country .
Russia will be an issue in November , but a Communist victory would make it more of one .
administration officials can do little more than wait and watch as Russians make their choice .
David Ensor , ABC News , Moscow .
In an election in Romania , there is more than the usual interest .
former tennis star Ilie Nastase is in the run-off election for mayor of Bucharest .
Although not expected to win , Nastase says he will stay in politics .
China and the U.S. are playing it down to the wire .
Trade talks in Beijing have produced no agreement .
The U.S. has threatened to impose sanctions at noon on Monday , but officials could decide to make that noon our time , giving the talks 12 hours to avert a trade war .
The U.S. wants China to crack down on factories pirating American CDs and films .
Still ahead : Whitewater committee Republicans point an accusing finger at the First Lady ; a disturbing in the black church burnings ; and getting their kicks on Route 66 .
this Father 's Day , we bring you the story of a difficult journey through the generations .
It 's going on in a prison in Pennsylvania .
Here 's Alexander Johnson .
Sentenced to this prison , these men knew they faced hard time together , but were surprised to learn what else they have in common .
I had no relationship with my father
He beat me as a child , verbally abusive .
what they have in common with juvenile offenders from this area .
Drugs and alcohol was more important than I was to him , and that- hurt inside .
I would stick notes under his pillow saying , `` I hate you , I hope you die . '
Forced to their physical limits at this boot camp , these inmates must face emotional tests , in a parenting program called HOPE .
We took these youth who do n't have fathers , and brought them to dads who do n't have their children .
Words these dads never had the courage to speak to their own fathers they now write and read out loud .
`` Dad , I have feelings .
They hurt to this day .
The sad thing is , I grew up to be like you . '
Many hate the fathers they have become .
A good father would n't be in prison .
Right ?
I do n't think I was selling drugs
For most of the men , confronting their past is the most painful part of the program , but it 's the first step in resolving the rage they feel toward their fathers , and the shame with their children .
`` It might seem strange , getting a letter from someone you have n't seen or heard from in over 10 years .
It might seem stranger , knowing that person is your father . '
John Mitchell was convicted of telemarketing fraud .
With 17-year-old Erin playing his daughter , he reads a letter he 's afraid to send .
`` Because I did n't have the courage to talk to my daughter . '
The roles reversed , John listens to Erin , who abused drugs when communication with her father failed .
`` all the bad things I did was a cry for my father to wrap his arms around me , and tell me he loved me . '
Lessons about how to build healthy relationships , lessons John and the other inmates , who graduated back to society this week , must put to use at home .
I do n't know if I can be the perfect dad .
I will do my best , and I 've learned to keep an open ear , communicate , and just love .
A second chance at fatherhood .
Alexander Johnson , ABC News , Lewisburg , Pennsylvania .
Mrs. Clinton is at the center of this investigation , because she had an independent life - first as a lawyer , and then as an active and politically involved First Lady .
Michele Norris on some of the questions .
The questions started when the Clintons were campaigning four years ago .
Can we ask Mrs. Clinton ?
Sure .
Ask her whatever you want .
On the issue of Whitewater , Mrs. Clinton denied representing her partner Jim McDougal 's bank before state regulators .
My firm has done work for the bank .
That 's right .
I have done work for the bank not related to the state
the billing records found quarters at the White House contradict that claim .
On the travel office firings two years ago , the First Lady claimed that she had nothing to do with it.
that claim was challenged by a memo which quoted Mrs. Clinton as saying , `` We need those people out .
We need our people in. '
in the wake of Vincent Foster 's suicide , documents were removed from his office ; a charge Mrs. Clinton denied .
under congressional inquiry , the First Lady 's advisers undercut her credibility with a case of amnesia .
I do n't remember .
I do n't recall .
I have no recollection .
The Clintons accuse their critics of bombarding them with questions to keep them on the defensive .
problems like Whitewater stay afloat because while the questions keep coming , the answers change .
Michele Norris , ABC News , Washington .
Bob Dole is campaigning in the Golden State , hoping to cut into Bill Clinton 's lead in the polls .
A survey shows the president leading Dole in California , 57 percent to 34 percent .
A year ago , Dole lead Clinton in California 47 percent to 42 percent .
Bruce Morton is in Woodland Hills with the Dole campaign .
any reaction to these numbers ?
what they say is one poll is one poll , and it 's just that - a moment in time .
It may be accurate , it may not .
this is a Field poll , and some of the staff have reservations about Mervin Field 's polls .
He has been wrong in the past , so they are tending to downplay it.
It does n't reflect this California swing .
This is the start of Dole 's California campaign .
Ken Kachigian is aboard as the man in charge .
He has a plan - where you go , what to do , what to talk about .
Dole , undisciplined as a speaker , this time has been good about that .
He is not talking about Whitewater , he is not talking about the FBI files .
He was on message , a defensive end , a farm event , and illegal immigration .
If the federal government does n't want the responsibility of taking control of our borders , then they ought to turn it over to the states .
the federal government ought to be able to control the borders , and we should n't stick the states with billions of dollars of expenses .
each year an additional 300,000 individuals are in our country illegally .
And of them come to California .
each illegal entry is an affront , not just to the laws of the United States , but to every immigrant who came to this country legally .
recent history in California suggests the voters are in a flighty mood .
Governor Pete Wilson was behind Kathleen Brown by 23 points .
He wound up beating her by 15 .
That 's a 38-point swing , and Kachigian and others working on the Dole campaign love to talk about those numbers .
Bernie ?
Thank you , Bruce Morton in Woodland Hills , California .
A survey shows that managed care health plans are a bargain compared to traditional health insurance and for some patients they are easier to use .
But not all doctors think HMOs are good for their patient 's health .
This doctor saved a man 's life by taking on the insurance bureaucracy that had given up on him .
I told him that I had a hard time with a 39-year-old person who wants to live , and not trying .
Steven Herod was dying of heart failure , which had caused his stomach to swell .
his HMO considered his condition too complicated and too expensive .
They told you it was not-
-They told me it was not treatable , and they basically did n't want to have anything to do with me .
they did n't tell him that if he got some experienced surgeon , who could do this kind of surgery , that that was a possibility .
Deerfield , on duty when Herod arrived in the emergency room , went to bat for him and with the help of a congressional aide , found the money to pay for his operation .
she 's one of the few doctors willing to lock horns with the establishment , because she has cut all ties to it.
I would come home crying almost every night , telling my husband about this patient or that , or-
Deerfield quit over common practices , such as paying bonuses to doctors for not referring patients to specialists , creating roadblocks that lead to delayed or denied care , and rules preventing doctors from telling patients about treatments not covered by the HMO .
At a time when nine out of ten doctors are under at least one managed care contract , Deerfield is becoming a rare breed .
patient advocates are discouraged , either because of the gag law , or peer pressure .
As more doctors sign up with managed care plans for economic survival , Deerfield 'll take her chances on the outside .
she 'd rather quit medicine than practice on terms she cannot accept .
Dan Rutz , CNN , Los Angeles .
Sunday will be a day for Greeks to remember their former prime minister , Andreas Papandreou .
He has died at the age of 77 after months of failing health .
CNN 's David Compton joins us with a look back at a colorful and controversial political figure .
Papandreou was educated at Harvard .
in 1974 he founded the socialist Pasok party .
He would rule the socialists for more than two decades .
In 1981 , he took the nation by storm .
His socialists came to power in a landslide election victory and Papandreou was Greek prime minister .
he vowed to pull Greece out of NATO and the European Union , promises he never kept but which won him support .
Health problems sapped some of his energy .
He had open-heart surgery in London in 1988 .
he arrived back in Greece with his young mistress , a former airline flight attendant .
He divorced his wife and declared this mistress the new first lady .
He married her a year later .
Scandals about his private life he could fight off.
a political scandal forced Papandreou out of power .
In 1989 , he was accused of helping to embezzle hundreds of millions of dollars .
With the scandal , and the economy turning sour , the socialists fell out of favor and Papandreou became Greece 's former prime minister .
It was a title he would not hold for long .
In 1992 , he was cleared the financial scandal and was again elected prime minister .
time had mellowed Papandreou .
He still knocked heads with European and U.S. leaders , but his rhetoric had been toned down .
He began to court the economic help of other Western nations , and talked of privatizing state-run industries .
In his final years , Papandreou shied away from public appearances and Cabinet meetings became less frequent .
it was failing health , not political rivals , that ended the Papandreou era .
David Compton , CNN , reporting .
Ted Kaczynski has a new home while he awaits trial on attacks linked to the Unabomber .
The Montana recluse has been transported to California .
Don Knapp joins us live from Sacramento with a look at what 's next .
Theodore Kaczynski is not far from us right now .
He 's in the building behind me .
He 's on the eighth floor in a cell .
It 's the Sacramento County Jail , where he has been since mid-day .
it is unlikely we will have any more photo ops of the man known as the Unabomb suspect .
A U.S. marshal 's plane brought Kaczynski a day earlier than expected .
Following a hearing Friday , marshals here said Kaczynski would arrive Monday evening .
He arrived Sunday morning at Mather Field 15 miles east of Sacramento .
Officers took the suspect into an armored vehicle and drove in a seven-car motorcade to County jail .
While he 's charged with some egregious crimes , his conduct in custody has been the contrary .
He 's placid , calm , sedentary , all the time .
Does nothing more than read .
Kaczynski occupies a cell on the eighth floor with a view of Sacramento , where two Unabomb victims died .
We may have seen the last pictures of Kaczynski .
Plans call for trips to court to begin in a garage beneath the county jail and end in a garage beneath the federal courthouse , where cameras are not allowed .
Kaczynski faces charges contained in a 10-count indictment naming him as the person responsible for transporting bombs and bomb parts from Montana to California and mailing them to victims .
the Unabomb task force says the suspect was responsible for 23 injuries and three deaths over a 17-year period .
, back to you .
Thanks , Don .
The fuss over secret FBI files inside the White House grew louder today .
One Republican contends some of the records contain private taxpayer documents .
If true , some staffers could face criminal inquiries .
A law makes it illegal for anyone to look at your tax papers without permission .
Mark Feldstein looks into this embarrassment for the White House .
files obtained by the White House on officials from Republican administrations included IRS as well as FBI records .
Republican Senator Charles Grassley says his staff discovered IRS documents while reviewing the files .
Grassley wants an explanation .
The FBI declined to comment
White House Spokesman Mark Fabiani said he does n't know if any of the files include confidential tax information , because the White House has returned all files to the FBI .
FBI files are one thing - that 's bad enough .
IRS files are worse .
Don Alexander was the IRS commissioner under Richard Nixon .
Nixon used the IRS to dig up dirt on opponents .
Alexander helped pass post-Watergate reforms to prevent that from happening again .
I do n't want clowns in the White House to go back to days I thought were finished .
I was dumb and naive to believe that Watergate and some of its abuses could not happen again .
Now , I question that belief .
It 's unclear what IRS records made their way to the White House , how many files are involved , or how they got there .
Officials are trying to track the files that ended up at the White House .
a source told CNN that the White House has n't released the names of at least five other Republicans whose FBI files they obtained .
The White House says it 's turned over everything it has .
Republican Congressman William Clinger requested that the White House provide more documents on the affair , including records of any reprimands of Livingstone .
Sources tell CNN that Livingstone was reviewed by an administration official for talking about the background reports .
It all heats up this week .
Two congressional committees plan to hear public testimony from the White House officials involved .
some will have to be subpoenaed to testify .
Mark Feldstein , CNN , Washington .
The junk bond market heating up .
Companies have issued $ 19 billion of junk bonds this year .
That 's a gain of 70 percent from a year ago .
Kathleen Behof reports from Chicago .
Retailers , drug makers , cable companies - they 're issuing high-yield bonds at a frantic pace .
The amount of junk issued this year is up 72 percent from last year .
Companies need money to fund growth .
Many of these had done initial public offerings of stock last year .
They are so capital-intensive , they need more cash to go forward and to countries all over the world .
They 're having an easy time finding buyers .
Sales of junk bond mutual funds are outpacing corporate bonds , while government , municipal and mortgage bond mutual funds are reporting a net outflow .
High yields are outperforming other bonds .
experts say investors are chasing yield , but they 're also looking for a way to diversify portfolios .
When K-Mart issued $ 1 billion of convertible preferred securities that yielded 7.75 percent , buyers were waiting in line .
What makes a more efficient portfolio , to add this asset class to an existing portfolio .
we 're seeing some of that in terms of high weekly cash flows into the high-yield sector of the bond market .
Quality is getting better in the high-yield sector .
That 's because corporate cash flows are improving .
Experts say this year 's pace is not likely to beat the record reached in 1993 , but investor demand will remain robust .
Kathleen Behof , CNN Financial News , Chicago .
The New York Stock Exchange is looking into whether the Bank of New York gave preferential treatment to large investors .
in a conference call with analysts , the bank said it boosted credit card reserves by $ 350 million .
The problem - that conference call took place before the markets closed .
The news was not released until after the closing .
That gave big investors an advantage in trading of stock .
Bank of New York said it regrets the move and is taking steps to prevent a recurrence .
Victory for small pharmacies across the country .
A federal judge approved a $ 351 million settlement against big drug makers .
That deal would give small pharmacies the same drug discounts offered to HMOs , hospitals and mail order retailers .
The first settlement did not give the drug stores equal access to pricing deals .
I 'm Carolyn O'Neil and welcome to On The Menu .
with summer upon us , it 's time to head outdoors and fire up the backyard grill .
according to the Barbecue Industry Association , 91 percent of folks say they like to cook outdoors because they love grilled foods .
cooking outside means you have to pay attention to food safety .
It 's summertime and the grilling 's easy .
summer is no time to relax when it comes to food safety .
according to the United States Department of Agriculture , there is an increase in food-borne illnesses between May and September .
to keep summer foods safe , here are some tips .
When cooking ground beef , make sure it 's thoroughly cooked .
Undercooked hamburger can be a source of E. coli 0157H7 .
It 's difficult to test the internal temperature of a hamburger .
the best surrogate is the color of the meat and if you cook or ask for your hamburger brown in the middle , you cut your risk of getting E. Coli 157H7 or other E. coli .
with more than burgers on the grill , it 's important to pick up skills in cooking other meats .
The Pork Producers Council recommends using a meat thermometer to make sure pork is cooked to an internal temperature of 155 degrees .
you can learn the tongue test .
I will take my tongs or my fork and touch the surface of the pork chop .
If there 's a bit of give , they 're done perfectly .
If there 's a lot of give , you need to put it back on the grill and if it 's real hard , you 've gone too far .
