Reporter Jennifer Griffin , heading south from Beirut , joins us by phone from Tyre .
Good morning , Jennifer .
Hello .
What are you seeing on the coast road ?
the cars are bumper to bumper all the way .
People are packed 10 and 12 per car .
They have mattresses strapped to the roofs of their car
They 're not sure their houses survived the bombing and where they 're going to sleep tonight .
people have tied black ribbons to their antennas in memory of the people who have died in the last 16 days .
how much faith do they put in this cease-fire ?
they 've seen war and cease-fires , but this is going to hold .
it 's going to last , but for how long .
it 's a matter of time before there 's more fighting .
How bad is Southern Lebanon ?
Are the roads open ?
Are the villages habitable ?
It 's unbelievable .
The roads from Tyre to the smaller villages are cratered with bomb holes .
the roads are impassable , and the cars are stopped while the U.N. tries alternative routes , but it 's really difficult because these are mountainous areas .
The destruction is massive .
many homes along the route are rubble and combined with the craters in the road , it 's quite a scene .
What about reconstruction ?
are there plans to begin reconstructing ?
there are some plans .
The French have offered to bring two transformers in , but the government estimates it 'll cost about $ 80 million to get the electricity back up and running .
What did the future look like to the people you 're speaking with ?
people are trying to get on with their lives .
They 're worried about their homes and are trying to make them livable again .
I talked to one boy who five days ago was hit by an Israeli shell .
He was sitting in his house in Yadir , which is near Khana , and his face is scarred from burns , and his family ca n't reach their home because the road is destroyed , but they 're waiting for the U.N. .
his house looks like a carton with the edges folded in , and he says that he 's going to be ready next time , he 's going to join Hezbollah .
Thanks , Jennifer .
Thanks , Neal .
Jennifer Griffin speaking from Lebanon .
The Whitewater verdicts have caused embarrassment for Arkansas ' Republican Lieutenant Governor , Mike Huckabee .
Since Democratic Governor Jim Guy Tucker is resigning , Huckabee will be taking over the governor 's office .
Huckabee is the GOP nominee for a U.S. Senate seat .
Is a statehouse in the hand worth a senate seat in the Beltway ?
Huckabee will let everybody know tomorrow .
heeding strategists ' or his own political instincts , Bob Dole is mum about Whitewater .
he has not been silent about crime and the president 's record on it.
Tomorrow Clinton will endorse communities to use curfews to curb gang violence .
It was an issue Dole addressed today .
More from Candy Crowley .
On a hit-and-run campaign swing through California , Dole stopped in a Southern California park to praise community anti-gang efforts .
They made it work , because they tired of it.
They wanted their children to enjoy the parks , not the criminals , They were n't built for criminals , they were built for you .
Crime is the focal point of Dole 's trip to California .
Mr. President , you took off three years .
You were AWOL .
You were without leadership on the drug program for years , and election year conversion is not going to do any good .
This trip out west had overriding .
Dole is here , not for the first time .
Not for the last .
we 're going to California if it takes weeks , we want to win this state .
no trip to California will be more important to Dole than the one in August .
Dole dropped by the San Diego Convention Center for a peek at where he will officially become the Republican nominee for president .
-have a great party .
It 's going to start the road to victory here .
Being here is important to California Republicans , who think they lost local seats when George Bush abandoned the state months ahead of the election .
Ken Kachigian , former Reagan operative in charge of Dole 's California efforts , says step one is showing up.
step two is an aggressive campaign to redefine President Clinton , to start letting people get exposed to Dole .
it 's a long trip .
The Dole campaign hopes to pick up support on three issues of California - crime , border patrol , and affirmative action .
Dole supports a California initiative which would dismantle most affirmative action programs .
As for Whitewater , Dole will let others parse politics .
As Kachigian put it , when there 's a freight train coming down the tracks , it does n't make sense to stand in the way
Candy Crowley , with the Dole campaign , California .
Breaking news from the Air Force on the crash of that jet in Croatia the killed Commerce Secretary Ron Brown and the troupe that was traveling with him .
We go to Carl Rochelle at the White House , for that latest .
Carl .
the three commanders in charge have been relieved of duty .
Based on the investigation of the April 3rd crash that killed Ron Brown and his party , Major General Charles Heffelbauer , the commander of the 17th Air Force in Europe has lost confidence in the ability of the commander , the vice-commander , and the group operations commander of the 86th Airlift Wing which is based at Ramstein in Germany , and that is the unit that had the overview of that aircraft , a militarized version of the Boeing 737 .
That was with the concurrence of the commander of U.S. forces in Europe , General Ryan .
The relieved were Brigadier General William Stevens , a former commander of the 86th Airlift Wing ; Colonel Roger W. Hanson , former vice-commander of the 86th Airlift Wing ; and Colonel John E. Mazurowsky , former commander of the 86th Operations Group .
the men are being replaced , but there are no other further details available as to why .
they wo n't release any details of exactly what they discovered that led to this action until after the investigation is completed .
the three senior commanders involved in the oversight of the aircraft that took Ron Brown and his party to their deaths have been relieved of duty .
Leon .
right .
we understand you can tell us if any of their subordinates are going to be charged ?
there have n't been any charges .
the people in charge of the unit when the unit fails take the brunt in the military regime
It is unclear what they found in that investigation .
they never have come down with a reason for the crash .
It 's clear the aircraft was off course .
It was not flying directly to the airport , but off in the mountains .
the transportation command inside the United States had ruled that airport only safe for landing during VFR day-time weather .
That means a nice , sunny day or during the daytime , but not at night and not in inclement conditions .
But the unit in Europe had not done that .
Also the training and procedures might be into questions .
That remains to be seen .
right .
tell us where the brigadier general and the two colonels are right now
Do you know ?
The names
Do you know where they are ?
Do you know where they are ?
do I know where they are ?
They have not been sent back to the United States .
OK.
One would assume they 're in Europe .
All right .
Thanks .
Carl Rochelle reporting from the White House .
Thanks , we 'll see you .
talks did n't work , and mediators did n't help .
the FBI may be turning to a religious expert to help end the Freemen standoff in Montana .
A member of a religious think tank from Houston is meeting with federal agents .
CNN 's Don Knapp joins us from Montana .
Don ?
it is a rainy , muddy morning in Montana with no sign of activity on the Freemen ranch ; no sign of activity on the part of the FBI .
We know that work is continuing in an effort to put generators on the neighboring ranches so that the FBI will be able to shut off power to the Freemen .
there is some activity underway .
The FBI brought in a religious expert .
He is Philip Arnold , associate at the Reunion Institute in Houston and member of the Religious Freedom Task Force .
He is consulting with the FBI and the Department of Justice have not ruled out his acting as a negotiator .
They say he is an expert on this sort of situation .
He 's been critical of the federal government 's handling of Waco that cost many lives .
in Billings , Montana , yesterday , there was a hearing for two Freemen whose arrests triggered this standoff , along with three associates .
The hearing became unruly .
Two Freemen were evicted from the courtroom , and the judge did grant the prosecution more time to prepare for trial .
Bobbie ?
Don Knapp near Brusett , Montana , thanks .
What could be more frustrating than wasting time in traffic ?
imagine you read while a computer takes the wheel .
the era of automated driving could be down the road .
Smart Cars give `` back seat driver ' a new meaning .
the goal of the automated highway system- is to allow a commuter to sit back and make phone calls .
Scientists have been building driver-less vehicles for years .
Five years ago , the vehicle Nav Lab Two was bulky with computers and camera systems .
The gear enabled the computer to see the road .
Today , Nav Lab Five fits into a sedan , and can help if there 's someone at the wheel .
These vehicles are designed for automated steering , also to monitor drivers ' performance .
if I drift , it 'll trigger an alarm as the tires gets outside the lane .
The system relies on a video camera .
It looks for lane markers to keep the car on the road .
mounted below the rear view mirror , it looks ahead .
The image is analyzed by a computer powered by the cigarette lighter .
a Nav Lab van traveled from Washington to San Diego .
90 percent of the trip was controlled by the computer , everything but the breaks .
there were bumps in the road .
It has trouble in situations that drivers have trouble in .
one of the difficult situations is a rainy night with on-coming headlights .
it will be 10 years before automated driving , but the accident warning program could be added to existing trucks .
One in four trucks are in this kind of accident , so it would be a win for trucking companies for $ 2,000
make the highways safer by keeping an eye on the road and hands off the wheel .
Dick Wilson , Pennsylvania .
the future of the Middle East peace process will soon be addressed .
Israel 's new prime minister elect , Benjamin Netanyahu , will outline his policies Sunday in a speech .
He spent the Sabbath with family and friends .
the White House is trying to calm Netanyahu 's critics .
Netanyahu 's victory jarred many in the Arab world , but the Clinton administration has been in touch with Arab leaders reassuring them and urging them not to pre-judge the prime minister elect .
Clinton said , `` Give him time . '
we ought to give the new prime minister a chance to put his government together and develop a policy .
He says he wants to continue the process and I think the friends of peace in the Arab world will be committed to that .
Mr. Clinton cited comments by Netanyahu at the end of the campaign and a phone conversation the two had Friday .
The president was encouraged by comments from Jordan 's King Hussein whom Netanyahu telephoned after his victory .
He assured me that he was going to do whatever he could to bring our common objective , of a comprehensive peace in this area .
Netanyahu says he opposed return of the Golan Heights to Syria and creation of a Palestinian state .
it 's in Israel 's interest to preserve the gains it has made from the peace process and to maintain a good relationship with its neighbors .
I do n't think Netanyahu intends to kill the peace process .
he intends to bargain harder and not make as many concessions as his predecessors .
the world will not come to an end.
The Clinton administration has a vested interest in the peace process .
President Clinton has pinned a major part of his international policy reputation on it.
another challenge looms in another part of the world , as Russian voters decide the fate of Boris Yeltsin two weeks from now .
Jill Dougherty , the White House .
It was home to Al Capone and the Birdman .
For 30 years , the island in San Francisco Bay housed some of the worst criminals in the U.S.
Now , `` The Rock ' goes from the big house to the big screen , again .
Movie goers are gearing up to enter The Rock starring Sean Connery , Nicholas Cage , and Ed Harris .
They shot this tale on Alcatraz , the infamous prison that housed some savage inmates .
Alcatraz is an unsafe place to make a movie because there are cliffs and corroding pipes everywhere , and old nails
Alcatraz opened in 1934 , was shut in 1963 by Attorney General Robert Kennedy , due to its deteriorating conditions .
as director Michael Bay told us in filming The Rock , it 's downright creepy .
When you walk into the set , sometimes you 're alone in the main cell block and Al Capone lived here- it 's bizarre .
these cells are really small .
They 're five by seven , and they 're low ceilings .
They 're six-something .
Nicknamed `` The Rock , ' Bay 's film is not the first time Hollywood has romanced the stone .
last year , Kevin Bacon and Christian Slater probed brutality on Alcatraz in Murder In The First .
Burt Lancaster received an Oscar nomination for his Birdman of Alcatraz , while Clint Eastwood chipped away at the Rock in Escape From Alcatraz .
Escape ?
That 's what Sean Connery 's character did , as revealed in the movie .
His name is John Mason , a British national incarcerated on Alcatraz in 1962 .
The government needs Mason 's knowledge of the prison and the expertise of an FBI scientist played by Cage .
It 's a problem .
it 's like anything Stan Goodspeed has encountered before .
the Bay area is in dire jeopardy .
We 've put him in a circumstance where he really wants to survive and get out and he 's sucked in by this guy whose totally ill-equipped .
The job is to end a chemical weapons threat against the Bay Area by a maniacal Ed Harris .
You 're right .
I do n't use guns and I do n't kick down doors .
This is what I do .
I have n't got my glasses .
The combination of Connery and Cage provides comic relief from rapidfire shots .
His character and my character were perfect to get laughs .
these actors traded lines where inmates once traded insults .
Paul Vercammen , Los Angeles .
During the summit , Secretary of State Warren Christopher and Treasury Secretary Lloyd Bentsen dropped in on the inaugural meeting of the American Chamber of Commerce in Moscow and offered encouragement .
Instead of new aid , the Clinton administration is pushing private investment .
Long-promised government-backed loan guarantees for American businesses have finally kicked in , but businessmen in Russia feel like pioneers in a wild frontier .
NPR 's Anne Garrels reports .
Five years ago Alex Papacristo was one of the few American lawyers in Moscow and the only representing his firm , White & Case .
Now the office has 12 .
The Russian capital is awash in consultants .
Hotels have sprung up catering to the Western businessmen .
The break-up of the Communist Party has expanded business opportunities , but Papacristo says too much order has been replaced with too much chaos .
officials even if they want to help you , ca n't because they do n't control things anymore .
Nobody does .
the problem is reversed .
There 's no order , and it 's very hard to determine whether you 're talking to the right person .
Take the development of a major oil shelf off of Sakhalin Island .
New regional leaders balked at the deal the central government had approved .
Parliament got into the act.
Only after several years did American oil companies have a contract .
Foreign companies are frustrated by changing laws , arbitrary regulations , ineffectual courts , and a lack of infrastructure .
Yet , Alex Papacristo remains intrigued .
The ability to invest in privatized Russian companies is exciting .
There 's more of that .
It 's still in the order of hundreds of millions of dollars , which compared to American business in other countries is not huge .
But it 's getting bigger .
Papacristo says start small and find a good partner .
Donald Green , managing director of Planicon , says doing business in Russia requires time and a lot of spade work .
You have consumer companies who 're not manufacturing products in Russia but they 're developing the networks to sell their products throughout the Russian federation .
As order breaks down , theft becomes a problem .
If moving cigarettes or alcohol or perfume around Russia , the security of those shipments is of major concern .
I do n't regard those circumstances as dangerous as some of the worst stories of developing country business , but they 're significant .
Recent election results sent chills to the American business community , but Papacristo and Green are optimistic Yeltsin will use his powers to stop the parliament from making the business situation worse .
While American investment in Russia is unlikely to explode , both expect a steady increase .
both warn investment in Russia is not for the faint-hearted or the impatient .
Anne Garrels in Washington .
It 's All Things Considered .
I 'm Noah Adams .
I 'm Linda Wertheimer .
In Israel , Benjamin Netanyahu was declared the winner of last week 's election .
The prime minister-elect has 45 days to form new government .
One of Netanyahu 's tasks is to select his cabinet members .
As NPR 's Eric Weiner reports , the people he chooses will determine the course of the Middle East peace process .
Benjamin Netanyahu needed support to win last week 's election .
he 's under pressure to reward those who helped at the polls , Israel 's ultra-Orthodox Jews and hard liners within his own Likud Party .
David Makovsky , author of a book on the Oslo peace accord , says Netanyahu 's policies will depend on the people he decides to appoint .
is the pragmatic Netanyahu we saw on the campaign trail gonna be pragmatic as prime minister ?
Likud is a mixture of pragmatists , which Netanyahu 's one of , and ideologues .
Those ideologues include Rafael Eytan and Ariel Sharon , two former generals who orchestrated Israel 's ill-fated invasion of Lebanon in 1982 .
Sharon played a key role in Netanyahu 's campaign , and he 's insisting on a top cabinet position , possibly as head of the finance ministry .
Representatives from Israel 's religious parties are likely to receive two cabinet positions .
more moderate Likud leaders are also in line for top posts .
David Levy , foreign minister during the Likud 's last time in office , is likely to get his old job .
Another question is whether Netanyahu will share power with the man he defeated , Shimon Peres .
Israel 's two major parties have governed together before in the late 1980s , and Yossi Beilin , a minister in the Peres government , says , given the delicate peace process , it 's worth trying again .
it is the most delicate moment in the peace process , because we are going to refer to issues like the refugees , like Jerusalem , like the borders , and it is important that we will be there .
it is possible to find a a common denominator for the Palestinians , for the Labor Party , and for the Likud .
Prime Minister-elect Netanyahu has yet to propose a national unity government , nor has Shimon Peres expressed enthusiasm for the idea .
Analysts say a power-sharing arrangement is possible , though unlikely .
Meanwhile , Netanyahu is meeting not only with potential coalition partners , but with foreign ambassadors , including U.S. Ambassador Martin Indyk .
The topic , Indyk says , was Netanyahu 's upcoming trip to Washington .
The president is keen to meet with him and he will as soon as he 's formed the government - President Clinton , the secretary of state , committed to working with the prime minister-elect to advance the peace process .
One part of the peace process the U.S. has played a role in is Israel 's on-again , off-again talks with Syria .
After Netanyahu 's victory , those talks seemed to be in jeopardy , but now a top aide says the new prime minister would like to resume negotiations with more limited goals .
Analysts say it 's the first sign that Benjamin Netanyahu may try to advance the peace process
Eric Weiner in Jerusalem .
In Alaska , a wildfire which began Sunday has consumed 10,000 acres and continues out of control .
The fire is in the Matanuska Valley , 30 miles north of Anchorage .
It 's heavily forested country , laced with dirt roads and many homes .
It 's one of the fastest-growing regions in the state .
Hundreds of buildings have burned and more than 1,000 people evacuated .
Tom Boatner is a firefighter who 's been on the scene since Sunday .
We reached him at the high school in Houston , Alaska , where the forestry division set up an incident command post .
We are getting strong winds .
We 've had another wind shift .
We 're getting 25-mile-an-hour winds with gusts to 35 .
Conditions are dry , so the combination is making for radical fire behavior .
we 're seeing fire behavior that occurs maybe four times a century .
Tell me what you mean by radical fire behavior .
This is burning black spruce , white spruce and birch forests .
The top of the flames are another 100 feet taller than the trees , so we 're talking 150-foot flame lengths at the head of the fire .
The fire is so hot that we ca n't attack , meaning putting people and engines and pumps right on the fire line .
It 's too dangerous .
I ca n't imagine you could send people into an area where the column of fire was taller than a 20-story building .
No.
the last 48 hours we 've had one simple priority on this fire , do n't kill anybody .
In 21 years of fire fighting , this is as dangerous a situation as I 've ever seen .
this fire is rolling through heavily forested country with hundreds of homes scattered through the forest , and our firefighters are focused on trying to save homes .
fire breaks and soaking them and fire retardant , that kind of thing .
right .
with these conditions we 're not able to do anything without water , so almost all of the protection has been with fire engines .
Fire engines .
Yeah .
the wildland type of fire engine and we have volunteer fire engines from all over the state .
we 're going to continue prioritizing structure protection , but today we 're going to nail down some perimeter so we can stop it galloping across the countryside .
Describe how you do that .
we 're putting on the perimeter hand crews , engines , bulldozers , water tenders - all supported by helicopters with buckets and retardant bombers .
we knock down the flames and the heat on the very perimeter of the fire and then put out all the hot spots and secure that perimeter so the fire ca n't advance .
thanks .
You 're welcome .
Tom Boatner is operations chief for this fire .
a smoke jumper for the Bureau of Land Management based in Fairbanks , he spoke to us from Houston High School in Houston , Alaska .
In the ranch occupied by the so-called Freemen , a letter by a jailed cult leader may have played a role in the first departures since April .
Brian Jenkins reports on day 75 of the standoff .
He joins us live .
Brian ?
we have a development just three minutes ago .
Two members of the Freemen on the 960 acre property came to the entrance to meet with two FBI agents who had been there for a half an hour .
They pulled their vehicle down .
It 's the four wheel drive vehicle we have seen many times .
They appear to be talking .
About what we do not know .
One of the state legislators who served as an intermediary in this 75 day standoff said that negotiations could pick up now that a family of four left Thursday .
Gloria Ward , her husband Elwin , and Gloria 's two daughters , aged 10 and eight .
They were taken to the FBI command post in Jordan , about 30 miles southeast , then to Miles City , where a state judge granted temporary custody of the two girls to their aunt , Gloria Ward 's sister , and gave jurisdiction over the girls to the state of Utah .
They were taken to Billings .
They flew out of Billings this morning , and arrived in Salt Lake City .
you see Gloria Ward with long , dark hair , her two children- Courtney , 10 and Jay-Lyn , eight .
Jay-Lyn 's father lives in Utah .
The older girl 's father also lives in Salt Lake City , and they expressed relief that the girls are free .
Gloria Ward , belongs to a small sect of ex-communicated Mormons , called the House of Cheney , and Gloria 's sister asked the leader of that sect , John Cheney , to write a letter encouraging the Wards to come off the ranch .
We have two comments .
First , from the attorney for Lynn Nielsen , Gloria 's sister .
John Cheney asked God about them coming out and God said they should come out , that they had work to do outside the ranch .
We heard in a interview from John Cheney that he simply wrote the note encouraging them to leave .
They made their decision on their own .
He gave this interview from a jail cell in Provo , Utah , where he is charged with forcing his 13 year-old daughter to marry a 48 year-old .
Gloria Ward 's oldest daughter , now 15 , married John Cheney last year and became pregnant .
She is in the custody of child welfare officials in Michigan .
that situation stands with the Ward family , Gloria Ward and her two daughters in Utah .
Here on the Freemen ranch in Montana .
We have two FBI agents meeting with two members of the Freemen .
We will report further details when we have them .
Natalie ?
Brian Jenkins in Montana .
Thank you .
If sex education is a hotly debated topic in a open society , imagine what it 's like in a more traditional society like China .
you do n't have to .
Maria Ressa set in on a sex ed class and got a lesson on culture .
Their questions seemed naive .
What do you do if you like a boy ?
What if a teacher asks embarrassing questions ?
these are questions few here feel they can discuss .
This is China 's sex education to help adolescent girls and boys deal with growing up.
In two years , 30,000 students have participated in this course , and it 's caused some controversy .
Teachers are afraid because we never dealt with sexuality .
China 's education system demands a strict code of behavior from students .
It 's formal , rote-oriented teaching enforces discipline and respect for authority .
It also adds party politics and communist doctrine .
recent reforms have opened the country to Western influence in movies , television and music and that sends conflicting messages .
They see things and they want to try it .
they 're too young .
The class is straightforward .
A teacher addresses the changes in their bodies and speaks about topics normally considered taboo .
that encourages students like 14-year-old Chen Jing .
I just wish my parents and other teachers could be like this , so we could communicate .
It 's a conservative society .
Chen has no boyfriend and would not want one until college , but girls face an added problem .
They are the first generations of China 's policy which restricts couples to one child .
With no brother or sister to confide in , it becomes difficult to handle questions of sexuality , and skewed ratios of boys to girls may put pressure on them .
Chen says this class is a relief , helping her understand and deal with questions she could n't even talk about .
Maria Ressa , Beijing .
President Clinton left on a three-day campaign that could generate some controversy .
He 's leaving behind controversy about FBI files on some well-known Republicans .
Kathleen Koch is at the White House .
Kathleen .
Good morning , Joie .
the president left for three days of speeches and fundraising in Nevada , California and New Mexico .
in San Francisco , the president is likely to be met with protests from the gay community about his support for a bill that would deny federal benefits to same sex couples .
the president would prefer to face that than the furor that has erupted in Washington over the White House 's gathering of some 350 people 's FBI files , including some belonging to Republicans in both the Bush and Reagan administrations .
a mistake occurred in 1993 when an Army staffer was updating the list of people with clearance to enter the grounds .
that staffer was working from an outdated list , his replacement discovered the mistake and there were no more files then requested .
Republicans , including presidential candidate Dole , believe that there was more to it .
everything in this administration is always an innocent mistake .
it was a mistake .
we did n't know it was there .
we have to take this seriously .
It 's not good .
If this had happened in years past , what might follow .
the president can clear it up - if he apologizes to the American people .
White House Chief Panetta insisted that there was no wrongdoing , it was a mistake , but he apologized .
nothing was done with that information .
It was not passed on to any officials .
those files have been returned to the FBI .
A mistake has been made .
an apology is owed .
the White House has taken steps to make sure this never happens again .
FBI director Louis Freeh ordered new restrictions on sharing confidential information with the White House .
this change came in a letter to Pennsylvania Republican Congressman William Clinger , who spoke with Freeh about wrongdoing in this file controversy .
Joie .
Kathleen , thanks .
Kathleen Koch at the White House .
First , a story we 've been covering .
officials are trying to learn more about a violent incident mid-way between Tel Aviv and Jerusalem .
For the latest story , we 're joined on the phone by Jerrold Kessel .
what happened ?
some of the mystery surrounding this shooting is being cleared up .
About 11:15 , two hours ago , two people were killed , probably Israeli civilians , in a car .
They were shot on a road about 25 miles southwest of Jerusalem .
Police are treating this as a terror attack , but they 're not confirming that .
reports that gunmen had fired at a vehicle near an army base some 15 miles away from this attack towards the Gaza Strip , is now being discounted by the police .
they say , having set up roadblocks , rushed reinforcements to the area , there 's no evidence of any second shooting incident .
the confirmed shooting is being treated as a terror attack .
there 's no claim of responsibility .
A camera man who 's on site reports the car in a ditch on the side of the road with 10 bullets through its front wind screen , and that 's probably the reason police are treating it as a terror attack .
The people inside were dead , apparently an Israeli couple .
an infant was found unhurt , according to a spokesman for an ambulance service which went to the site of the incident .
Israeli security forces have been on high alert for attacks by Islamic militants during the Israeli election period , 10 days ago .
the Islamic militants have vowed resistance and attacks after the election of prime minister-elect Benjamin Netanyahu .
the site of the attack is not far from the open border between the West Bank and Israel .
That 's what we know .
Jeanne ?
what measures are authorities taking in response ?
after the rumors came in , police rushed reinforcements and patrol cars through the area , threw up roadblocks fearing there was a car on the loose with gunmen in a shooting spree .
They have set up roadblocks around a triangle between Jerusalem , Tel Aviv , and southwest of that area , in a country district .
They have thrown up roadblocks , but they have not found anything further than that attack in which the two people have been killed .
they are continuing to search the area to see if there were any further incidents .
No confirmation of anything beyond the single incident in which two people have been shot dead .
Jerrold Kessel in Israel , and we will bring you more details as they become available .
as the Russian election approaches , we hear from several observers about whether to extend Boris Yeltsin 's presidency or opt for Gennady Zyuganov 's communism .
that choice momentous , journalist Jonathan Steele says Yeltsin and Zyuganov appear campaigning on the same promises .
Yeltsin has stolen Zyuganov 's clothes over the last months .
He talks about reviving Russia as a great power , so it 's more nationalist language than we used to hear from Yeltsin when he was pro-Western .
he 's talking about spending more to help the poorest .
He 's talking about subsidizing the military-industrial complex .
He 's talking about controls on imports to protect industry , so this nationalist , protectionist , state interventionist policy which the Communists advocate is similar to what Yeltsin says he would do .
do you think this suggests a lack of conviction on Yeltsin 's part for the policies he advanced as president , or a tactical abandonment for the campaign ?
it reflects a change in Russian opinion over the last years .
there has been disillusionment with the market economy and a feeling that you have to correct it .
what Yeltsin is doing is partly tactical in that it 's the best way to get votes in the center of Russian opinion , but I think it is something he would stick to , if he won a second term .
You 're suggesting the political outlook of Russia 's Communist Party is more in tune with Russia of 1996 than the Yeltsin government over the past couple of years .
on two points certainly .
One is the economy , and the other is this sense that Russia has been humiliated over the last seven years .
The loss of empire mood , which Russians seem to have got over quickly at the time in 1990 and '91 , can be seen as a deep-seated wound that has n't healed , and the Communists are talking patriotism .
They 're talking about Russia having been humiliated and a need to stand on its own feet again , even if that means not being so pro-Western .
That 's the thing that Yeltsin 's taken on board .
the difference is which of these men , would be least likely to tamper with civil liberties and roll back the democratic reforms of Gorbachev .
Is Boris Yeltsin a democrat ?
Is he devoted to civil liberties more than Gennady Zyuganov ?
that is the big debate .
Take television .
All three television channels that have national coverage are now controlled by the president .
you could argue flippantly , that if you want an opposition media , vote Zyuganov , because then all the three stations would be against the new president .
that 's an illustration that Yeltsin has taken into his hands - in a way that we would n't think acceptable in a Western country - the main broadcast media .
On the question of rights to assembly , political parties and so on , be speculative .
Zyuganov , after 2-1/2 years as a parliamentarian - knows you ca n't go back to one-party rule , that you have to do deals , make coalitions , try and keep up dialogue with parties that do n't support you - has shown experience and loyalty to parliamentarism .
With Yeltsin , this is questionable .
He has refused to found his own party .
He did close down the parliament in 1993 .
He brought in a very authoritarian constitution which downplays parliament .
I think the jury has to be out on how much of a democrat Yeltsin is - or Zyuganov - because we know less about Zyuganov .
Jonathan Steele spoke to us from London .
He is an assistant editor of the newspaper , The Guardian .
He is a former Moscow bureau chief and author of Eternal Russia .
Over the past 18 months , churches with predominantly African-American congregations have been going up in flames in Texas , North Carolina , South Carolina , Tennessee , Louisiana , Alabama , Mississippi , Virginia , and Georgia .
Clergymen met with Clinton administration officials to talk about the federal response .
investigators are probing another suspicious blaze at a black church in Texas , while police say that they 've made an arrest in connection with the one that destroyed the sanctuary of a black church in North Carolina .
Al Hinman has details .
Al ?
pressure is mounting all across the country to make sure arrests are made .
In Charlotte , local city-county police officials , state and federal law enforcement agencies , all felt convinced they could solve this case very quickly and they did .
A investigation resulted in a juvenile being charged with setting the fire .
there is no information to indicate that this incident is connected to any national or local conspiracy .
There is also no evidence that this was racially motivated .
This juvenile has been served with a petition for violation of burning churches and is currently being detained in a juvenile detention facility .
Two Charlotte-Mecklenberg police officers obtained information through their sources , to make the initial investigation go in the direction of the suspect .
Additional information was supplied by citizens who called in and that helped lead to the quick arrest .
this incident has- no apparent racial motivation .
There may be other causes not being discussed .
A 13-year-old is in custody , a white female .
She has been charged with setting the fire that torched the 93-year-old Matthews-Merkland sanctuary that had not been in use for years .
this congregation and the city are working to heal the emotional wounds and show that they can march together , black and white .
Reid ?
right .
Al Hinman in Charlotte .
You may never see your face on the screen , but perhaps your house ought to be in pictures .
studios are on the look-out for the perfect house , finding it cheaper than building a set from scratch .
that casting call can be lucrative , but also cause headaches .
Fred Katayama reports .
Movie location scouts scour neighborhoods for a house with star quality , searching for homes with space for equipment plus 100 cast and crew .
A modest house can fetch $ 1,000 a day ; and a mansion can command a daily rate of $ 10,000 and up.
If your home is chosen , clear away romantic notions and focus on reality .
It 's hard to understand how all-consuming a process it is.
we 're in almost every nook and cranny of your house .
The owners of a San Francisco home used in Mrs. Doubtfire sued the film 's producers , claiming the house was trashed .
before the first frame is shot , nail down essentials .
Ask exactly what they want to be doing there and when ; get everything in writing .
In Filmed on Location , James Leonis says insist on a contract that sets out specifics , and make sure the studio has insurance covering any damage .
prepare for an invasion .
They started setting up around Thanksgiving , and now it 's June , and they 're still talking about shooting in our house .
Rob Kos ' New Jersey home is being used for The Devil 's Own , starring Harrison Ford and Brad Pitt .
Kos says the experience has been worthwhile .
It was a once-in-a-lifetime experience to see how movies are made ; we rolled with the punches , and it 's been great .
For most , stardom is a long shot .
to improve the odds , list your home with state and local film commissions and production companies .
That 's Your Money .
Fred Katayama , New York .
the government is calling the largest seizure of smuggled automatic weapons in American history .
seven people are under arrest , including two Chinese nationals with ties to the Chinese military .
Brian Ross is in San Francisco .
U.S. customs tracking shipments into this country led undercover agents to set up the illegal shipment this March of some 2,000 AK-47's , shown here being unpacked after they were seized in Oakland ; guns the undercover agents had claimed were destined for American street gangs .
They also negotiated even more sophisticated weapons - Stinger-type missiles and hand grenades that can kill many people .
at least seven others are being sought , including top officials in China .
The Chinese government is into this all the way up .
The case leads directly back to two prominent arms companies tied to the Chinese Peoples Liberation Army .
Poly Technologies is headed by the son-in-law of Chinese leader Deng Xiaoping .
the other , Norinco , manufactured the AK-47's seized in the government sting .
authorities told ABC News that agents were preparing to lure two Chinese officials to San Francisco when the sting had to be ended prematurely for fear it had been compromised .
Brian Ross , San Francisco .
In Serbia , President Slobodan Milosevic pledged to the United States that Bosnian Serb leader Radovan Karadzic will be effectively removed from power .
Mr. Karadzic , has been indicted by the War Crimes Tribunal .
Back in a moment .
Investors on Wall Street were quick to pick up the latest fashion trend - Saks Holdings .
The parent company of Saks Fifth Avenue offering a 26 percent stake in the company .
Investors rushed to buy the stock , ending the week up $ 8 from its initial offering price of $ 25 a share .
Luxury is in.
While the retail sector 's recovery has been spotty , the sky 's the limit for high-end stores .
Wall Street is betting that Saks will continue the trend .
The retailer will raise $ 400 million to wipe out more than one-third of its debt .
The wealthier consumers are benefiting from economic trends , and they 're spending money in stores like Tiffany and Gucci that are public companies , where the results have consistently been better than expected .
Tiffany recently split its stock after a big jump in quarterly earnings , and Gucci stock soared after a 113 percent jump in revenue .
Designer Donna Karan , sensing a friendly environment , is readying another attempt at a public offering .
the hunt is on for the next hot retailer , and some stores are wondering if they should answer Wall Street 's call .
We 've been sought after .
We are educating ourselves , they are educating themselves about us and when the time comes maybe we make the move .
Heads of private apparel companies worry about ceding control to share holders who may not agree how to run the business , but with conditions so favorable , more are getting over their fear of going public .
Kitty Pilgrim , CNN .
I declare the Disney Store in Manhattan officially open .
Walt Disney opening its latest store .
The three-story Disney Kingdom is in the heart of Manhattan and just a block and a half from Warner Brothers .
Disney paying $ 400 a square foot for the location , says the publicity is worth the price .
Dan Rutz joined a fitness expert to get advice on how to exercise without getting hurt .
It 's a steady flow of injuries .
He makes a living on the downside of fitness , but Dr. Thomas Branch , of Emory University , believes that the benefits of exercise outweigh the risk of getting hurt .
A workout should start with stretching .
80 percent of your stretch occurs in the first minute .
The cords that bind muscle to bone require special postures .
Muscles stretch best when gradually put to work .
Branch warms up on a stationary bike .
What about a jog or a walk ?
Would that accomplish the same thing as an exercise bike ?
That 's the same .
OK.
Yep .
Start out slow , get the muscles moving , and the jog becomes safer .
three out of four men in the CNN/Men 's Health poll say they 're in good shape , but national statistics find a third overweight .
Many quit exercising when they get hurt , but proper warmups and not overdoing it can prevent the `` itises ' - tendinitis , ligamentitis .
inflammation of a tight tendon can cause pain when you exercise and it is difficult to get rid of.
What are men in their 30s , 40s , 50s , and 60s doing running anyway ?
What 's the point ?
Why bother ?
The combination of stress management - exercise for your cardiovascular system to prolong life and limit disease , are the two main reasons .
Richard Krebs has a third reason .
He enjoys an active lifestyle though he 's coming back from an injury that required surgery .
I had an unfortunate occurrence .
There are risks in the world , and I do n't believe in sitting home and playing it safe .
He 's coming along with his strength .
Rehabilitation that is sport-specific helps reduce reinjury , and to avoid trouble , get to know your body , especially when things do n't feel right .
Once you learn , the next time symptoms appear you do n't have to go to the doctor .
Let me ask if we 're trading fitness for 40 for arthritis at 60 ?
you might be doing the opposite .
If you do the right amount and incorporate cross-training into your program , you may be prolonging your life and reducing arthritis .
Cross training means mixing up the routine with different activities .
instead of wearing out one part of the body , all of it will stay fit .
use it or lose it.
Dan Rutz , CNN .
The San Diego Zoo and Wild Animal Park hit the Web .
Explore the Gorilla Tropics Habitat , visit Mombassa Lagoon to see this white alligator or and hit What 's New to see some faces only a mother could love .
For cool science look at the Why Files .
This gives you the science behind the news , with topics explained in detail , from Mad Cow disease to comets .
The Cool Science Image area lets you see a butterfly 's nodes up close and other images from an electron microscope .
for more in-depth science information check out Access Excellence .
This is developed by the biotech firm Genintech to help high school biology teachers understand the biotech industry .
the What 's News area is full of easy to understand articles about current science issues , with an archive of hundreds more .
The Resource List links to science Web sites from NASA to interactive frog dissections .
http://.sandiegozoo.org
http://.whyfiles.news.wisc.edu
http://.gene.com/ae
When looking for a place to live some people insist on closet space , others wo n't take an apartment without a great kitchen .
on New York 's lower east side computer connoisseurs look for something different .
Norma Quarles has the story .
This new five story building is in a community better known for walk-up tenements and squatters doing battle with police than for high rent apartments .
this building has something computer users are willing to pay for : a T1 cable giving them high speed access to the Internet .
this is the the first building wired with T1 cable from its inception .
Josh Kilmer Purcell , an art director for an advertising agency , pays $ 1550 a month for a one-bedroom apartment and $ 85 a month for the service .
it has to do with speed .
I can work from here with my office here in New York , as well as the office in Atlanta .
I can do my layouts here .
At night I can retrieve files from those offices .
it 's invaluable .
they could charge more and I would still pay .
tenant John Brann is a technologist for a software company .
I 've been a regular Internet user for three years and the simple graphics on the Net can take ages to download through an phone line .
Apartments range from $ 1500 to $ 3500 a month .
The building opened in April and 25 of the 28 units are rented .
the fact that the building is wired for wide band access is something that I am prepared to pay for .
The editor of NetGuide magazine says this may not be for the average user .
most people can do well with a 2400 baud modem and a phone line .
we are seeing a combination of New York real estate and Internet hype but if people are willing to pay they must believe it is worth it.
Norma Quarles , New York .
on the subject of domiciles , if you ask any do it yourselfer , they will tell you that home improvement projects come in two kinds - success stories and unmitigated disasters .
on the Computer Connection , we will show you CD ROMs , that help ensure your next repair job does n't turn into a money pit .
We will be right back .
the first break in months at the so-called Freemen ranch in Montana .
A family of four leaves ; the wildfire in Alaska spreads ; and elsewhere interfering with Mother Nature make the problem worse .
forests are going to burn .
Senator Dole on abortion .
He would like the Republican platform to change .
this is World News with Peter Jennings .
Good evening .
We begin in eastern Montana .
There has been a change .
A family of four left the compound where the Freemen of Montana have been holed up.
They are the first to leave since April .
they leave after a week in which the FBI has visibly increased the pressure on the Freemen , who have on their ranch for more than 10 weeks .
Ron Claiborne on who comes out and who stays .
They left this afternoon , meeting two FBI agents on the road to the besieged compound .
The departure follows a discussion between the agents and those inside the vehicle .
Inside were Elwin Ward , his wife Gloria and her daughters from previous marriages - 10-year-old Courtney and 8-year-old Jay Lynn .
Gloria Ward had been facing a charge in Utah for allegedly denying visitation rights to the father of one of the girls .
authorities had agreed to drop the charges .
It is not clear why the family chose or was allowed to leave .
earlier this week , the FBI cut electricity to the compound .
Today 's departures may signal that increasing the pressure and new negotiations with the Freemen may pay off.
with 17 people still in the compound , including its militant leaders , there is no indication that the standoff is about to end.
Ron Claiborne , Montana .
video preview with Dennis Michael .
Grumpier Old Men is out .
we do n't want to comment
Nicolas Cage 's character has come to Las Vegas to drink himself to death , but he falls in love .
a best actor performance by Cage and a brilliant turn by Elizabeth Shue make this tragic tale irresistible .
grownups should n't miss it.
Grumpier Old Men is n't as good as the original , but Jack Lemmon and Walter Matthau are walking encyclopedias of screen comedy and the story line hardly matters except that it brings Sophia Loren into the mix .
This is a comedy that lives for the moment .
this movie 's moment passed a long time ago , but it 's only now coming to home video .
Heavy Metal was named after the science fiction magazine that inspired it , but it looks like somebody tried to make a movie out of old album covers .
rarely does this flick take flight .
Collectors only .
See you at the rental counter .
Dennis Michael , Hollywood .
Democrats accused Robert Dole of breaking federal law by overspending in his presidential campaign .
In April , Dole came close to the $ 37 million spending limit , in exchange for taking federal matching funds .
Democrats charge he exceeded the limit in May .
Peter Overby reports .
The Dole campaign spent heavily last winter trying to build his candidacy .
Pat Buchanan 's populism and Steve Forbes ' personal fortune made Dole keep on spending .
Don Fowler , chairman of the Democratic National Committee , says Dole knew the rules .
He made decisions to spend at a high rate .
He made those decisions .
He expended most of his money , and that he 's now forced to violate the law is his responsibility .
a complaint filed at the Federal Election Commission focuses on Dole 's campaign spending from May 1st to the GOP convention .
After the convention , both Dole and Clinton will get $ 62 million from the Treasury for the fall , but until then , the DNC 's analysis shows that Dole is out of money .
For the month of May , we determined the minimal costs that the Dole campaign spent , based on past patterns in their FEC reports and press accounts of campaign operations .
The Democrats documents support that the Dole campaign is already $ 343,000 over , that the Republican National Committee are paying for campaign activities and that there 's no way Dole can get through the convention without going over by a million dollars .
Dole denied his campaign has broken campaign finance laws .
He said Clinton is getting undisclosed support from organized labor , and that Clinton did n't have primary challengers .
he got a $ 10 million subsidy for his campaign , without any real opposition .
then organized labor laid down 35 million bucks .
Here 's 35 million . '
Dole got reinforcements .
Chairman Haley Barbour called a news conference after the Democrats .
It is a tactic of the left to try to win in court what you ca n't win at the ballot box .
This is a attempt by Clinton and the Democrat Party to divert attention from the bad news about their own legal and ethical problems .
Barbour released numbers from the Dole campaign .
It started out broke - but listed income , both real and anticipated , that the Democrats did n't .
it would come from selling assets of Dole 's primary campaign to the general election campaign .
Barbour said campaign spending ought to be deregulated .
We 've got a law that 's unfair .
Bill Clinton , as of May 31st , had $ 20 million for his general election .
He 's got to spend it for election purposes prior to August 29th .
Dole , because he had to win his party 's primary , has a million dollars .
That is unfair .
It is a stupid law .
The American people want competitive politics .
The Democrats are asking for action from the Federal Election Commission , but that body moves slowly .
the FEC fined Democratic leader Richard Gephardt for violations by his 1988 presidential campaign .
He paid the fine in 1995 .
Peter Overby in Washington .
Bob Dole is catching flack from another angle- the Democratic National Committee today charged he has played fast and loose with primary campaing spending limits .
Dole denies it.
Brooks Jackson has the story .
Democrats say Dole is flunking civics .
Democratic National Committee Chairman Don Fowler accused Dole 's campaign of violating pre-nomination spending limits by $ 343,000 and said the Federal Election Commission should keep the total from going higher , and he attacked Dole 's character .
This is about trust .
Dole pledged that in return for millions of taxpayer dollars , he would obey the law .
He has broken that promise and violated that trust .
a look at similar complaints shows this sword can cut both ways .
Clinton 's 1992 campaign was accused by auditors of gouging taxpayers .
Clinton 's campaign got federal matching funds for his primary campaign , based on contributions received after he was nominated .
FEC auditors wanted Clinton to repay $ 4 million ; the most ever .
the three Democratic commissioners vetoed that .
The FEC deadlocked .
The Clinton campaign has never ever been found guilty of violations of the Federal Election Campaign Act or paid penalties .
No civil penalties , but the Clinton campaign repaid taxpayers more than $ 1.3 million , after FEC Democrats softened the audit findings .
how about Democratic leader Richard Gephardt ?
The FEC found his 1988 presidential campaign over the spending limit in Iowa by $ 450,000 , 60 percent higher than allowed .
He had to give back $ 120,000 .
Candidates have been overspending since limits were enacted .
Reagan went $ 30,000 over the limit in New Hampshire in 1976 , and $ 55,000 over in 1980 .
in 1980 , Jimmy Carter overspent in Iowa , New Hampshire , and Maine .
Ted Kennedy also broke the limits in Iowa and New Hampshire .
Limit-busting has n't worked as a campaign issue .
In 1984 , Gary Hart attacked Walter Mondale for using delegate committees to evade limits .
give the money back .
Give the money back .
Hart lost , though he was right .
Mondale paid $ 350,000 to the FEC .
Democratic Senator John Glenn 's opponents keep bringing up $ 2 million in bank loans to his '84 presidential campaign , loans the FEC said were illegal .
People are still waiting for their money !
John Glenn - he keeps owing .
Glenn won that '92 campaign and those loans are still not paid off.
Dole denied overspending and pointed to Clinton 's use of federal primary funds against Dole .
I 'm concerned about Clinton getting $ 11 million from the FEC when he did n't have an opponent .
he ought to refund the $ 11 million .
However Dole 's spending plays out , do n't expect a legal decision soon .
George Bush violated the primary spending limits in 1988 , and it took the FEC until last December to close the case , with a letter telling the ex-president do n't do it again .
the ball could be on its last bounce for the NBA season .
The Chicago Bulls and Seattle Supersonics are facing off.
Chicago could take its fourth championship of the decade with one more win .
Jeff Flock joins us .
how you doing ?
it is a wild night .
This is Michael Jordan 's Restaurant in Chicago but not particularly good news for the Bulls tonight so far .
they are trailing the Seattle Supersonics by 21 points at halftime , so it 's time to show you Michael Jordan 's Restaurant .
you see soaring Michael two or three stories over Chicago painted on that restaurant .
this city concerned the Bulls can pull it out and claim victory tonight , concerned that they do n't have a repeat of 1992 .
That is when the Bulls won their second NBA championship , second of three in a row - problems on the streets that night - looting , cars overturned .
the city made a concerted effort , spending $ 3 million on security and putting together a public service announcement , featuring Bulls coach Phil Jackson , Michael Jordan and an unlikely candidate - Dennis Rodman .
we 're in this together .
If we win , celebrate with style and dignity .
This Chicago 's moment to shine .
Let 's show the world how to do it .
That is what they hope happens - the Bulls clinch the championship - however things not looking well .
We will continue to dance with the folks and hope that things turn out for the best .
We 'll continue to watch
reporting from Chicago , Jeff Flock .
Back to you .
Bob Dole 's first day as private citizen and full-time presidential candidate may not be all he had hoped .
his Senate exit yesterday left him with a `` empty feeling , ' reinforced when he called his office today and no one was there .
That did n't distract Dole from courting voters in Ohio and projecting the attitude of both a regular guy and a winner .
Marc Watts is with the Dole camp .
first for Dole - changing the name of his campaign plane to Citizen 's Ship .
it was called The Leader 's Ship .
the former Senate majority leader embarked on his first campaign trip as a private citizen .
First stop - Toledo , Ohio .
George Strait 's song `` Heartland ' welcomed Dole at a luncheon for the Toledo Chamber of Commerce .
America 's Heartland is the theme of the Dole campaign trip .
I 'm going around the country to see where they have the best unemployment benefits and I thought I 'd check out Ohio and then go to Kansas .
His speech was an extension of his farewell remarks before Congress , but today the tone was more partisan .
I 'm going to run on my agenda .
It 's going to be my agenda for America and for the future .
I do n't have any animus towards President Clinton .
he called to tell my goodbye , and I 'm going to call him November 5 .
Dole reflected on his years in Congress , promising supporters the same commitment .
Running for president is a full-time job , and I have all the time I need to focus and to get the job done , because the stakes could n't be greater .
this trip is a chance for Dole to showcase himself as a regular person .
he 'll travel to Kansas to his roots , and he 'll be more open and engaging as the campaign continues .
The former Senate leader will visit eight states in three days , and he 'll return to Ohio several times before the election because it 's an important swing state .
I 'm determined to criss-cross America between now and November 5 .
Ohio knows something about picking winners .
Only twice in 100 years has Ohio not selected the winner in a presidential race , and no Republican has ever won the White House without winning Ohio .
Marc Watts , Ohio .
a DC-10 with 275 people on board crashed today just after takeoff in Fukuoka , Japan .
At least three people are dead , dozens more injured .
Garuda Airlines Flight 865 was en route to Jakarta , Indonesia .
Tom Mintier , joins us by telephone in Tokyo .
what can you tell us ?
What 's the latest ?
three people are dead .
The hospitalized has risen to 100 and 12 people are missing .
the fuselage is too hot for investigators to enter , and there is a fear that that those listed as missing are trapped in the back part that has burned .
Garuda Indonesia Flight 865 was airborne for a couple of minutes , lifted off the runway a few meters before slamming back down .
There is a possibility that engine problems attributed to this crash .
flames could be seen coming from the aircraft before the impact .
The Fukuoka International Airport is 2,000 meters long .
Most international airports that service large planes like this are 4,000 meters , and it may be a contributing factor .
The pilot began his lift-off and that was when the problems began .
Emergency rescue crews were on the scene within minutes and conducted the rescues and the firefighting effort simultaneously .
Many were able to slide down the emergency chutes .
There was criticism of the stewardesses , saying that they did not conduct emergency evacuation procedures properly .
the passengers on board the plane were indicated to go out exits that were on fire .
part of the investigation will not only center around the cause , but the action of the employees of the flight .
three people are listed as dead , 12 are missing , and more than 100 are hospitalized after this plane crash this morning here in Japan .
this particular aircraft , the DC-10 - do we have any information on this aircraft and its safety ?
We do n't have any information about this individual aircraft .
The DC-10 has had engine failures before .
There are going to be parts of the investigation looking at that .
There was a large gaping hole in engine number two , mounted on the tail , that could be seen as it sat , broken in half , at the end of the runway .
This is not a part that burned and experts have not been able to explain why that hole is on the side of the engine .
It 's possible that one of the jet 's turbines cut loose and ripped through the fuselage but it 's something investigators will take a look at.
experts are puzzled by this crash .
What about weather conditions ?
Has that been ruled out as contributing to this incident ?
Airport officials say the weather at the time of takeoff was not a factor- .
during the rundown of the runway the tower asked the captain to change radio frequencies , but the captain did not respond .
he was already having trouble controlling the aircraft and did not respond when he was told to change radio frequencies by the tower .
Tom Mintier by telephone from Japan .
Thanks , Tom .
Stay as we look into this developing story from overseas .
Andrea ?
political analyst , Bill Schneider , is in Washington .
aside from the legal concerns , as a political matter , what problem is this for the administration ?
this Whitewater committee is dominated by Republicans .
It 's partisan .
the report is being prepared by the Republican majority in this committee .
the voters will recognize this is a partisan document .
Far more serious were the convictions of associates of the Clintons ' - James and Susan McDougal , the governor of Arkansas , Jim Guy Tucker - by a jury of citizens in Arkansas .
that would create more damage .
this does focus the public on mysterious behavior by the White House .
No smoking gun , but questions being raised .
most Americans concluded the White House must be hiding something .
The disappearance of the Rose Law Firm billing records , the handling of the Foster documents , the FBI records taken by the White House , the contacts between the White House and the Treasury .
those suggest that the White House is hiding something .
What are the political considerations for the Republicans writing this report ?
They 've got to be careful how they handle the first lady .
that 's the debate they 're having now .
Whether they hold her culpable- then it ratchets up the whole investigation to a much higher level because then the Republicans taking on the first lady becomes a more serious matter .
It makes it more serious and more political .
OK.
Bill Schneider , Bob Franken in Washington .
you both have a cold .
get better over the weekend .
It 's not easy to figure out what 's going on in the brain of an infant .
researchers say there is more happening than previously thought .
Lisa Price explains .
Born prematurely , Kara is 38 days old.
her mother is helping her fight stress .
It 's no joke .
studies show the emotions and environmental factors which influence adults also influence infants .
Research by the Families and Work Institute suggest brains develop earlier than previously thought .
this knowledge has overwhelming cultural ramifications .
Kids attending this day care center are receiving the attention they need .
those who do n't may always been impaired , socially and emotionally .
I do n't care what you do .
if you take money and dedicate it to treatment .
You ca n't build things that did n't grow in the first five years .
Touch , eye contact , sensory stimulation help the brain grow .
The evidence is in.
Scientists have looked at the first years of life .
the uterus is the basic building block that will determine the success or failure of children later in life .
we 're seeing more tragic examples of failures .
Surges in kid crime , where children feel little remorse about what they 've done .
They do n't have remorse .
They regret they got caught .
Regret is an intellectual response .
Remorse is an affective , emotional response .
They do n't have that .
the irony is that those important years are the ones given the least attention .
It 's culturally foolish .
Lisa Price , Chicago .
the Russian presidential run-off appears certain between President Boris Yeltsin and Communist Party leader Gennady Zyuganov .
the stakes are high for Russia and the world .
our world affairs correspondent joins us from Moscow .
Ralph ?
in Moscow , Boris Yeltsin is edging out Communist Party challenger Gennady Zyuganov in the first round of the election , but not by enough to avoid a runoff .
With 50 percent of the votes counted , Mr. Yeltsin leads Mr. Zyuganov by about 3 points .
The third-place candidate is retired Army General Alexander Lebed , who has enough votes to make him a target for political bargaining already beginning here .
On Russian television , which has ignored everyone but Mr. Yeltsin , Lebed suddenly appeared for an interview .
General Lebed would begin military reforms tomorrow if Mr. Yeltsin appoints him to a government post .
for the army reform I need power .
If I get authority I will look up to the expectations people have .
Mr. Lebed conceded that his time has not come to be president of Russia .
skeptics speculated Boris Yeltsin might approve fraud to guarantee a victory .
More than 1,000 international observers have been watching the election .
One , in an interesting twist , is former U.S. Central Intelligence Agency director James Woolsey , who once inspected Russia through spy satellites .
I asked Woolsey about his observations .
The small town of Klim , outside of Moscow where our group from the Jamestown Foundation was today , things appeared to be going well .
It was stirring and touching .
The balloting was taking place near where the Russians stopped the Nazis in World War II .
I thought both Hitler and Stalin were turning over in their graves to see a free election in Russia with precinct captains and people coming in happily to the polls , flowers in front of the constitution in celebration .
It was nice .
From your observation of the procedures was there an opportunity for any kind of cheating ?
The procedure seemed , at the precincts we visited , simple and effective .
One ca n't tell about the voting lists , and there 's no way for observers to tell about what might happen in some central location .
the fact that this is all paper ballots and paper counting would suggest that if something were done to adjust the results , it would be fairly straight forward to check up on it.
at the half dozen precincts I visited people seemed to be taking this very seriously
They were coming to the polls dressed up.
They seemed serious about filling out their ballots .
Tell us what you observed .
Exactly .
They were happy .
There were differences .
We did some informal exit polling and found a large number for Yeltsin and a smattering for other candidates .
people could say what they thought .
they did .
with about 58 percent counted , Boris Yeltsin leads Gennady Zyuganov by 35 percent to 32 percent , and Russia is poised for a runoff election probably in three weeks .
Jill , Martin ?
OK , thank you , Ralph .
Boris Yeltsin has the most votes in Russia 's presidential election .
Mr. Yeltsin will face Communist Gennady Zyuganov in a runoff next month .
Mr. Yeltsin captured 35 percent of the vote and Zyuganov 32 percent .
Former General Alexander Lebed finished third with 15 percent of the vote .
Democracy is new to Russia and the biggest issues were the economy and character .
Claire Shipman reports .
Russians had already expected Yeltsin and Zyuganov .
He may be running a liberal paper , but to Viktor Skyorastan , the news of Yeltsin 's lead was disappointing .
He is a Zyuganov man .
Yeltsin promises , but never comes through .
his wages have dropped substantially in the last five years .
He ca n't afford to take his family on holiday .
polls show Russians cast their ballots based on their pocketbooks .
Chechnya , crime , paled by comparison .
Oxsuna and Amaryna gambled on Yeltsin and will again .
My life is better .
It 's not that I like him , but I do n't think it will get worse with him .
Lets leave things the same .
The support for General Alexander Lebed , seemed to reflect an equally deep desire for order .
We 've had dictators and now bandits .
We need a normal , trustworthy person .
life is hard without instability and worry about tomorrow .
Russians took the election results in stride , hardly surprised and not looking forward to another politically charged few weeks .
Thirty percent did n't vote .
would I vote ?
I 'm an engineer , a pensioner .
I live below the poverty line selling flowers .
But more than a million Russians - 1,142,000 - did vote for the uncandidate .
None of the Above came in sixth on the ballot of 10 .
Claire Shipman , Moscow .
Federal agents , state lawmakers , and others tried to keep the Freemen talking through their 81-day standoff .
The content of those talks was kept secret , but a Colorado legislator gave Jim Hill an inside glimpse .
before the 16 Freemen walked off their Montana ranch and into custody , their anger and threats spilled over in negotiations .
You 're going to save my life by imprisoning me ?
Colorado State Senator Charles Duke recorded his efforts .
12 armed Freemen said government officials had no jurisdiction over them .
I did n't stand up for this country to have the American people out here on their ass.
they can take their warrants .
Russ Landers is getting agitated and I 'm not sure he 's going to whip out his gun and plug me- .
May 21 the negotiations broke off.
When Duke failed in his efforts to mediate , he placed the blame on the Freemen , saying many were criminals trying to avoid prosecution .
the talks over , the Freemen resumed their patrols , but Freeman Edwin Clark became a key force inside the ranch .
the FBI tried to convince Clark to be a leader and counter the other Freemen , but Clark agonized .
He did n't want violence , but did n't want to turn people over to authorities , either .
The day the mediations failed , Clark was near despair .
I 've little faith in me , and when I give up things goes to hell .
It created a great deal of stress .
He was n't comfortable and it took weeks to assert himself .
the turning point came when the Ward family left the ranch on June 6 .
that convinced Clark to press the others to surrender .
June 14 they did .
Jim Hill , Colorado .
the political contests are heating up as the election approaches ; added to normal election year politics are Whitewater , a budding scandal over the use of the FBI by the White House to uncover information about rivals , and more .
The result is a stronger showing in the polls for Bob Dole .
Joining me now to put some perspective on Washington , Steve Bell , head of the Steve Bell Group .
He joins us every Monday .
good to have you with us.
Glad to be here .
the latest polls indicate Mr. Clinton 's lead over Bob Dole has narrowed to single digits .
What 's going on ?
we have to be careful about polls this far from the election , but there 's no doubt that about four weeks ago , the president 's momentum slowed .
It was n't just the Whitewater investigation and the convictions that Special Prosecutor Ken Starr got in Arkansas .
It was also the mistake of claiming the Soldiers and Sailors Act and active duty and things like that .
Dole got a boost by leaving the Senate ; and the FBI files used by the White House have drawn criticism from Lou Freeh , head of the FBI .
this is on top of an interesting report released officially tomorrow by the Whitewater committee of Congress .
the Whitewater report indicates criminal charges should be considered for some senior administration officials .
Have you heard anything ?
yes .
The rumors are rampant , with some of the document leaked , that three members of the White House staff might be recommended for criminal prosecution .
there 's still this subterranean notion that perhaps Hillary Rodham Clinton , would be indicted if the allegations are true .
Do you believe that , or are you skeptical ?
you just do n't know .
It 's unprecedented , and so much has been coming out in dribs and drabs that it 's hard to tell .
between this and the FBI files and the next round of the trials on Whitewater , the White House is going to be doing more legal work , than campaign work .
Whitewater 's been one problem .
The other one , the FBI search of records of Republican officials .
Which one 's hurting the president more ?
you 're going to see more damage from the files .
This breach smells
right .
we lost the ability to hear Steve ; and we will have to live without knowing his answer to that question , but the president 's having a difficult time in the polls .
We 'll have Steve back Monday morning to bring us more .
The Clinton administration is going to expand funding for an experimental program called the Brownfield Project , designed to spur investment in abandoned industrial sites .
John Chambers applauds the move .
For years , I have practiced environmental law in Washington , D.C.
My practice has taken me from Congress to the EPA and into the federal courts that decide the validity of EPA 's interpretation of congressional mandates .
In its role as primary protector of the environment , EPA dances to Congress ' tune .
it is surprising that EPA would undertake a major new program as part of its brownfields agenda .
`` Brownfields ' is used to refer to abandoned industrial sites that are environmental problems .
They take the form of abandoned warehouses , factories or vacant lots .
Those in cities pass by them daily .
The Government Accounting Office estimates there are more than 450,000 brownfield sites across the country .
Many are located in inner city communities where the population is working class minority groups .
The idea is to develop solutions to urban blight caused by environmental policies that discouraged private investment in areas hurt by contaminants from old industrial operations .
In addition to providing seed money , EPA set about revising its environmental clean-up and liability guidance to encourage buyers , lenders and developers to become involved in brownfield redevelopment .
It spearheaded changes to the Community Reinvestment Act to encourage greater participation by financial institutions .
The Clinton administration unveiled a new means to encourage brownfields redevelopment in a tax incentive proposal .
15 years as an environmental lawyer has taught me many things .
our collective lack of appreciation for the environment in the past has caused many of the problems we have today .
excessive regulation in the area of environmental clean-ups has impeded progress that might have been undertaken voluntarily .
EPA 's brownfields action agenda creates incentives to do the right thing , not only for the environment , but for people hurt by the conditions the nation 's poor communities .
It is time for Congress to get funding for an integrated approach to solving the problem of urban blight .
If legislation is passed to carry out brownfields redevelopment initiatives , it will be rare .
John Chambers in Washington , D.C.
Dole ignored the Whitewater and FBI files as he spent a second day courting California voters .
Dole 's in the Golden State promoting a stronger defense .
This Lockheed plant in Sunnyvale , California , is working on the THAD missile , a more sophisticated Patriot anti-missile .
employment is down to 10,000 , compared with 25,000 in 1986 .
Dole accused President Clinton of dragging his feet on defense .
Mr. Clintons opposition to a missile defense is negligent , short-sighted , irresponsible and potentially catastrophic .
it encourages missile attacks .
From Libya to Iraq to Iran to North Korea , a rogues gallery of terrorists and aggressive anti-American regimes , are being encouraged by the administration 's attitude .
Dole would speed development of this plant 's THAD and of missile defense in general .
He noted that people do n't believe politicians and linked that with his decision to leave the U.S. Senate .
I put my career on the line , because America 's future 's on the line .
That 's how important it is.
now it 's up to you .
reactions ?
Here are a few .
The guy has ideas .
that 's the problem with politicians today .
They want to be president , but they do n't have an idea what they want to do , except to be president .
He 's down to earth and I thought was true to what American people want .
They want to have security .
Dole stopped to visit a volunteer fire station , noting that his father and grandfather had been firefighters .
Clinton 's defense policies hurt California .
he 'll say other Clinton policies have done the same thing .
he goes to talk about agriculture .
Bruce Morton , California .
an F-18 fighter has crashed and burned 25 miles northeast of St. Louis , Missouri , operated by McDonnell Douglas , the manufacturer of the aircraft .
With more we turn to the Pentagon and Jamie McIntyre .
Jamie , what do you have ?
Pentagon sources tell us this was not a U.S. military plane , it was an older F-18 once used by the Navy , but now being leased back to McDonnell Douglas for its own purposes .
Pentagon sources tell us that the pilot , whose fate we still do n't know , was a McDonnell Douglas test pilot .
the F-18 crashed in a residential area northeast of St. Louis , Missouri , the headquarters of McDonnell Douglas , where the F-18 is manufactured .
McDonnell Douglas is working on a new , improved F-18 model .
This was not one - this was an older C model plane .
we 're still waiting on whether the pilot escaped injury , and whether or not anyone was hurt on the ground .
Miles ?
they were trying to test some retro-fitting to this older C model .
Do we know anything about those tests ?
No .
We 've made inquiries to McDonnell Douglas .
they have not been willing to talk
they say they 'll get back to us.
right .
Jamie McIntyre at the Pentagon .
we will keep you posted .
Dr. Jack Kevorkian has , apparently , attended the 31st suicide .
joining us by telephone is Geoffrey Fieger , Dr. Kevorkian 's attorney .
Mr. Fieger ?
Yes
Thank you
Sure .
can you confirm Dr. Kevorkian was present at this suicide ?
Yes .
Dr. Kevorkian and other physicians assisted Betty Lou Hamilton of Columbus , Ohio , end her suffering from a disease destroying her spinal cord .
Can you tell us a more about Ms. Hamilton ?
Who was she ?
She was 67-year-old woman who suffered for years from springo mayalia , which destroys the spinal cord .
She described it as having thousands of ice picks tearing into her body .
She was treated at the Ohio State University pain clinic .
It is incurable , and she has been counseling with Dr. Kevorkian for six months .
Mr. Fieger , how long Ms. Hamilton had been in contact with Dr. Kevorkian ?
six months .
OK.
where was the body found ?
It was n't .
It was brought by her friend to the Pontiac Osteopathic Hospital in Pontiac , Michigan , where doctors confirmed the death and treated the family with respect and compassion .
Mr. Fieger , thank you
We 've been speaking with Geoffrey Fieger , Dr. Jack Kevorkian 's attorney .
The abortion issue is divisive for Republicans in Texas .
the party is headed for a showdown at the state convention .
the outcome will determine who will choose the party 's nominee this August .
Texas anti-abortion activists have drawn a line in the sand on the state Republican Party 's position .
This convention has decided to say , `` We 're not sending pro-aborts to San Diego to change our party platform .
they face Senator Kay Bailey Hutchison .
a tolerance provision is important for the Party .
That has some Republicans wanting to block Hutchison out of the national convention as a delegate .
She should be pushed out .
I agree with that .
she 's not for the family .
Delegates were asked to sign this pledge by anti-abortion advocates seeking to send a majority .
But Hutchison received a vote of confidence from the other Texas senator , Phil Gramm , who says , if Hutchison does n't go , neither will he .
we heard from a minority and they 're bullies .
Bill Price , head of Texans United for Life , spearheaded the fight against Hutchison .
In reference to Gramm 's Democratic challenger , Price says if Gramm does n't go some in the party wo n't mind .
he should buy a little pickup and drive around Texas during the convention .
Anti-abortion activists in other states had success getting a majority of their delegates to the national convention .
Hutchison could be the highest-ranking official to be shut out .
party elders are pleading for unity .
We 've some differences , we can come out united for November , and that 's my goal .
Texas Governor George W. Bush says he wo n't tolerate a fight .
There is no compromise as far as Kay Hutchison .
She ought to be a delegate to the national convention .
Hutchison 's following here may think Kay is OK , but the controversy is n't the start the Republicans wanted heading to the national convention .
Senator Hutchison did receive a warm welcome from the crowd here .
But since Bob Dole made his plea for tolerance on abortion in the Republican Party , the stakes for them are even higher .
Paul Caron , Texas .
A royal update from columnist Mitchell Fink .
Hi , Mitchell .
Hi , Jim , Princess Diana knows how to get the most out of a photo opportunity .
Take last week when Di visited Chicago .
the men she danced with were her height or taller .
perspective partners had to be pre-approved before they could take their turn on the dance floor .
Sarah Ferguson was in Los Angeles last week and she visited studios to have meetings involving TV projects .
Fergie wants a career in television .
speaking of the Four Seasons , Arnold Schwarzenegger did n't make friends there during the press junket for his movie Eraser .
when Schwarzenegger was n't boasting about himself to the journalists , he was condescending to people .
Eraser opens June 21st .
finally Steven Spielberg will not be going on the new $ 110 million Jurassic Park ride .
designed to his specifications , Spielberg himself gets queasy around Jurassic Park , which climaxes with a drop of 84 feet into water .
I ca n't blame Steven for not wanting to go
I 'm getting queasy reporting it.
I 'm with you , Mitchell .
Jim Carrey went to The Cable Guy premier with old girlfriend Lauren Holly .
are you hearing about their reunion ?
they did go together .
they were broken up but this is a difficult time for Jim Carrey .
a year ago Jim Carrey was catapulted into the heights of fame , he 's getting $ 20 million for Cable Guy with a budget that 's probably twice that , Carrey is hearing negative stories about Cable Guy .
There 's negative buzz about this movie .
it opens , .
I do n't think he wants to be alone .
This is not a good time for him to be alone .
Who better than Lauren Holly ?
Good enough .
Thanks .
see you next week .
right .
Okay .
we 'll see the you right after this .
Do n't go away .
Gillian Findlay , reporting from Moscow .
The fallout of this election will not just be felt within the Russian borders .
There are poll-watchers in Washington , seriously hoping their man will win .
David Ensor explains .
The possibility of a victory by the Communist candidate sends shivers not only through Yeltsin 's Kremlin , but through President Clinton 's White House , too .
A Communist victory would be bad news in an election year .
The question from the Republicans would be `` Who lost Russia ? '
The political message sent by a Communist victory is they did n't get it right , and there 's a new problem for U.S. foreign policy .
the administration 's top expert on Russia , deputy secretary of state Strobe Talbott , says there are contingency plans in case of a Communist win , and if they abandon the road to reform , the U.S. would stop loans for Russia .
President Clinton will drive home the point that his administration is prepared for any outcome .
if Yeltsin does win , policy towards Russia will be an issue in the U.S. presidential race .
President Clinton has delayed action on enlarging NATO , putting the threats of Russian nationalists before the aspirations of democratic countries like Poland , the Czech republic , and Hungary .
I believe there 's a tendency to identify the future of Russia with one Russian leader .
U.S. officials always saw Yeltsin as imperfect .
he drank on the job , ignored corruption , and took the advice of cronies to launch in Chechnya a disastrous war .
with his ratings in the single digits two months ago , Yeltsin impressed Russians with an energetic campaign .
Two months ago , I was in panic .
Now we 're thinking about the future .
we keep our finger- fingers crossed , because everything could happen in our unpredictable country .
Russia will be an issue in November , but a Communist victory would make it even more of one .
Yet Clinton administration officials can do little more than wait and watch , as Russians make their choice .
David Ensor , Moscow .
In an election in Romania , there is more than the usual interest .
That 's because former tennis star Ilie Nastase is in the run-off for mayor of Bucharest .
Although the tennis great is not expected to win , he will stay in politics .
China and the U.S. are playing down to the wire .
Trade talks in Beijing have produced no agreement .
The U.S. has threatened to impose sanctions at noon on Monday , but officials could make that another 12 hours to avert a trade war .
The U.S. wants China to crack down on factories pirating American CDs and films .
ahead on World News : Whitewater committee Republicans point an accusing finger at the First Lady ; a trend in the black church burnings ; and getting their kicks on Route 66 .
On Father 's Day , we want to bring you the story of a difficult journey through the generations .
It 's in a prison in Pennsylvania .
ABC 's Alexander Johnson .
Sentenced to prison in Pennsylvania , these men knew they faced hard time together , but they were surprised to learn what else they have in common .
I had no relationship with my father
He beat me as a child .
what they have in common with many juvenile offenders .
Drugs and alcohol was more important than I was to him , that- hurt inside .
I would stick notes under his pillow saying , `` I hate you , I hope you die . '
Forced to physical limits at boot camp , inmates must also face emotional tests , in a unique parenting program called HOPE .
We took youth who do n't have fathers , and brought them to dads who do n't have their children .
Words these dads never had the courage to speak to their fathers they now write and read out loud .
`` Dad , I have feelings .
They still hurt .
I grew up to be just like you . '
Many hate the fathers they have become .
A good father would n't be in prison .
Right ?
I do n't think I was selling drugs
For most , confronting their past is the most painful part of the program , but it 's the first step in resolving the rage toward their fathers , and the shame with their own children .
`` It might seem strange , getting a letter from someone you have n't heard from in 10 years .
It might seem stranger , knowing that person is your father . '
John Mitchell was convicted of fraud .
With 17-year-old Erin playing his daughter , he reads a letter he 's too afraid to send .
`` I did n't have the courage to talk to my own daughter . '
The roles reversed , John listens to Erin , who abused drugs when communication with her father failed .
`` the bad things I did was just a cry for my father to wrap his arms around me , and tell me he loved me . '
Lessons how to build healthy relationships , John and the inmates , who graduated back to society , must put to use .
I do n't know if I can be the perfect dad .
I will do my best , and I 've learned to keep an open ear , communicate , and love .
A second chance at fatherhood .
Alexander Johnson , ABC .
Mrs. Clinton is at the center of this investigation , along with her husband , because she had an independent life - first as a private lawyer in Arkansas , and then as an active and involved First Lady .
Michele Norris on the questions .
The questions started when the Clintons were campaigning four years ago .
Can we ask Mrs. Clinton ?
Sure .
Ask her whatever .
On Whitewater , Mrs. Clinton denied representing Jim McDougal 's bank before Arkansas regulators .
My firm has done work for the bank .
right .
I have done work for the bank not related to the state
the billing records found in the White House contradict that claim , showing she did contact the state 's chief regulator on behalf of that bank .
On the travel office firings , the First Lady claimed under oath that she had nothing to do with it.
that claim was challenged by a memo from a White House staffer which quoted Mrs. Clinton saying , `` We need those people out .
We need our people in. '
in the wake of Vincent Foster 's suicide , there was testimony documents were removed from his office ; a charge Mrs. Clinton denied .
under inquiry , the First Lady 's closest advisers undercut her credibility with a collective case of amnesia .
I do n't remember .
I do n't recall .
I have no recollection .
The Clintons accuse their critics of bombarding them with never-ending questions to keep them on the defensive .
an examination of the First Lady 's statements suggest that problems stay afloat because while the questions keep coming , the answers often change .
Michele Norris , Washington .
Bob Dole is campaigning in the Golden State , hoping to cut Bill Clinton 's lead in the polls .
A new survey shows the president leading Dole in California 57 percent to 34 percent .
A year ago , Dole lead Clinton in California 47 percent to 42 percent .
Bruce Morton is in California , with the Dole campaign .
any reaction to these numbers ?
first , one poll is just that - a moment in time .
It may be accurate , it may not .
second , some of the staff have reservations about Mervin Field 's polls .
He has been famously wrong in the past , so they downplay it.
It does n't reflect this California swing .
This is the start of Dole 's California campaign .
Ken Kachigian is in charge .
He has a plan .
Dole , undisciplined as a speaker , has been good .
He is not talking about Whitewater , not about the FBI files .
He was on message , and this morning 's issue - illegal immigration .
If the federal government does n't want the responsibility of our borders , then they ought to turn it over to the states .
we ought to be able to control the borders and we should n't stick the states with billions of dollars of expenses , particularly California .
each year an additional 300,000 individuals are in our country illegally .
of them come to California .
each illegal entry is an affront not just to the laws of the United States , but to every immigrant who came to this country legally .
in polls , recent history in California suggests voters are in a flighty mood .
Governor Pete Wilson was behind Kathleen Brown by 23 points .
He wound up beating her by 15 .
That 's a 38-point swing , and the Dole campaign love those numbers .
Bernie ?
Thank you , Bruce Morton in California .
A survey shows managed care health plans are a bargain compared to traditional health insurance and for some easier to use .
not all doctors think HMOs are good for their patient 's .
This doctor saved a life by taking on insurance bureaucracy .
I told him that I had a 39-year-old person who wants to live .
Steven Herod was dying of heart failure , which caused his stomach to swell to grotesque proportions .
his HMO considered his condition too complicated and expensive to handle .
it was not-
-They told me it was not treatable , and they did n't want to have anything to do with me .
they did n't tell him that if he got some experienced surgeon , that that was a possibility .
Deerfield , on duty when Herod arrived in the emergency room , and a congressional aide , found the money to pay for his life-saving operation .
she 's one of few doctors willing to lock horns with the managed care establishment , because she has cut ties to it.
it was so bad that I would come home crying every night
Deerfield quit over common managed care practices , such as paying bonuses for not referring patients to specialists , creating roadblocks that lead to delayed care , and preventing doctors from telling patients about treatments not covered by the HMO .
when nearly nine out of ten doctors are under at least one managed care contract , Deerfield is becoming a rare breed .
people that are normally patient advocates are discouraged , either because of the gag law , or because of peer pressure .
As doctors sign up with managed care plans for economic survival , she 'll take her chances .
she 'd rather quit medicine than practice on terms she cannot accept .
Dan Rutz , Los Angeles .
Sunday Greeks remember their former prime minister , Andreas Papandreou .
He died at 77 after months of failing health .
CNN 's David Compton now joins us with a look a controversial political figure .
Andreas Papandreou was educated at Harvard .
He became a power player in Greek politics in 1974 , when he founded the socialist Pasok party .
He would rule the socialists for two decades .
In 1981 , he took the nation by storm .
His socialists came to power in a landslide election victory and Andreas Papandreou was prime minister .
he vowed to pull Greece out of NATO and the European Union , promises he never kept but which won him support at home .
Health problems sapped his once boundless energy .
He had open-heart surgery in 1988 .
he arrived back in Greece in true Papandreou style - with his young mistress , a former airline flight attendant .
He divorced his wife and declared this mistress the new first lady of Greece .
He married a year later .
Scandals he could fight off.
a political scandal forced Papandreou out of power .
In 1989 , he was accused of helping to embezzle millions of dollars .
With the scandal and the economy turning sour , the socialists fell out of favor and Papandreou became Greece 's former prime minister .
It was a title he would not hold for long .
In 1992 , he was cleared of any connection to the financial scandal and was again elected prime minister .
time mellowed Papandreou .
He knocked heads with European and U.S. leaders , but his rhetoric had been toned down .
He began to court the approval and economic help of other Western nations , and talked of privatizing state-run industries .
In his final years , Papandreou shied away from appearances and Cabinet meetings became less frequent .
failing health , not political rivals , ended the Papandreou era .
David Compton , CNN .
Ted Kaczynski has a new home while he awaits trial on attacks linked to the Unabomber .
The Montana recluse has been transported to California .
Don Knapp joins us from Sacramento .
Theodore Kaczynski is not far from us .
He 's in the building behind me .
He 's on the eighth floor in a cell .
It 's the Sacramento County Jail , where he has been since mid-day today .
it is unlikely we will have any more photo ops of the man known as the Unabomb suspect .
A U.S. marshal plane brought Kaczynski from Montana a day earlier than expected .
Following a hearing in Helena Friday , marshals said Kaczynski would arrive Monday .
He arrived Sunday morning at Mather Field 15 miles east of Sacramento .
Officers took the suspect into an armored vehicle in a seven-car motorcade to Sacrament 's County jail .
While he 's charged with egregious crimes , his conduct in custody has been quite the contrary .
He 's very placid .
Does nothing more than read .
Kaczynski occupies a cell with a view of Sacramento , a town where two Unabomb victims died .
We may have the last new pictures of Kaczynski .
trips to court begin in a garage beneath the county jail and end in a garage beneath the federal courthouse , where cameras are not allowed .
Kaczynski faces a 10-count federal indictment for transporting bombs and bomb parts from Montana to California and mailing them to victims .
the task force says the suspect was responsible for 23 injuries and three deaths over a 17-year period .
back to you .
Thanks very much .
The fuss over FBI files inside the White House grew louder today .
One Republican now contends the records contain private taxpayer documents .
some White House staffers could face criminal inquiries .
A post-Watergate law makes it illegal for anyone to look at your tax papers without permission .
Mark Feldstein looks into this election-year embarrassment for the White House .
files obtained on officials from Republican administrations allegedly included IRS as well as FBI records .
Republican Senator Charles Grassley says his Judiciary Committee staff discovered IRS documents while reviewing the controversial files .
Grassley wants an explanation .
The FBI declined to comment
White House Spokesman Mark Fabiani does n't know if any of the files include tax information , because the White House returned its files to the FBI .
FBI files are bad .
IRS files are worse .
Don Alexander was the IRS commissioner under President Nixon .
Nixon used the IRS to dig up dirt on opponents .
Alexander helped pass reforms to prevent that from happening again .
I do n't want the White House , to go back to days that I thought were finished in this country .
I was naive to believe that Watergate abuses could not happen again .
I question that belief .
It 's unclear what IRS records are involved , or how they got there .
Officials are trying to track FBI files that ended up at the White House .
a source close to former White security chief Craig Livingstone told CNN that the White House still has n't released the names of at least five Republicans whose files they obtained .
The White House says it 's turned over everything .
Republican Congressman William Clinger requested the White House provide more documents .
Livingstone was reviewed by an administration official for talking about the sensitive background reports .
It heats up further .
Two congressional committees plan to hear public testimony from the White House officials involved .
some will have to be subpoenaed .
Mark Feldstein , Washington .
The junk bond market heating up .
Companies have issued $ 19 billion of junk bonds this year .
That 's a gain of 70 percent from a year ago .
Kathleen Behof reports from Chicago .
Retailers , drug makers , cable companies - they 're issuing high-yield bonds at a frantic pace .
The junk issued so far this year is up 72 percent from last year .
Companies , especially media , telecommunications and cable , need to fund growth .
Many of these companies had initial public offerings of stock last year .
They need more cash to go forward - building wire , building cable and bringing television programming to countries all over the world .
They 're having an easy time finding buyers .
Sales of junk mutual funds are outpacing corporate bonds , while government , municipal and mortgage bond mutual funds are reporting a net outflow of money .
yields are vastly outperforming other bonds .
Fixed income experts say investors are chasing yield , but they 're also looking to diversify portfolios .
When K-Mart issued $ 1 billion of convertible preferred securities that yielded 7.75 percent , buyers were waiting in line .
What makes a more efficient portfolio , to add this to an existing portfolio .
we 're seeing that in these high weekly cash flows into the high-yield sector of the bond market .
Quality is getting better .
corporate cash flows are improving due to a strong economy .
Experts say this pace is not likely to beat 1993 , but demand will remain robust .
Kathleen Behof , Chicago .
The New York Stock Exchange is looking into whether the Bank of New York gave preferential treatment to large investors .
in a conference call with analysts the bank said it boosted credit card reserves by $ 350 million .
The problem - that call took place before the markets closed .
The news was released to the public after the closing bell .
That gave big investors an unfair advantage in trading stock .
Bank of New York said it regrets the move and is taking steps to prevent a recurrence .
Victory for small pharmacies across the country .
A federal judge approved a $ 351 million settlement against big drug makers .
That deal would give small pharmacies the same drug discounts offered to HMOs , hospitals and mail order retailers .
The first settlement in May , did not give the drug stores equal pricing deals .
I 'm Carolyn O'Neil and welcome to On The Menu .
with summer officially upon us , it 's time to fire up the backyard grill .
It not only gets you out of that hot kitchen , but according to the Barbecue Industry Association , 91 percent of folks say they cook outdoors because they love the taste of grilled foods .
cooking outside means moving further from the refrigerator and you have to pay closer attention to food safety .
It 's summertime and the grilling 's easy .
whether you 're flipping fish or a burger , summer is no time to relax when it comes to food safety .
It 's not clear whether cookouts are to blame , but according to the United States Department of Agriculture , there is an increase in cases of food-borne illnesses between May and September .
here are some tips .
When cooking beef , make sure it 's thoroughly cooked .
Undercooked hamburger can be a source of the deadly bacteria E. coli 0157H7 .
It 's difficult to test the internal temperature of a hamburger .
the best surrogate is the color of the meat and if you cook hamburger or ask for your hamburger brown in the middle , you cut your risk of getting E. Coli 157H7 or other E. coli .
it 's important to pick up skills in cooking other meats .
The Pork Producers Council recommends using a meat thermometer to make sure pork is cooked to at least 155 degrees .
you can learn the tongue test .
I take my fork and touch the surface of the pork chop , .
If there 's a little bit of give , they 're done perfectly .
If there 's a lot of give , you need to put it back on the grill .
